from flask import Flask, session, g, redirect, request as freq, url_for, render_template
from datetime import datetime
from config import config
from models.db import init_extensions
from models.setting import AppSetting


def _get_platform_settings():
    """Fetch all platform settings in ONE query for efficiency."""
    try:
        rows = AppSetting.query.filter(AppSetting.key.in_([
            'platform_logo', 'platform_name',
            'platform_tagline', 'platform_version',
            'support_whatsapp', 'support_email',
        ])).all()
        d = {r.key: r.value for r in rows}
        return {
            'platform_logo':     d.get('platform_logo', ''),
            'platform_name':     d.get('platform_name', 'Estroid Gold ERP'),
            'platform_tagline':  d.get('platform_tagline', 'Smart ERP System for Gold Factories'),
            'platform_version':  d.get('platform_version', 'v5.0'),
            'support_whatsapp':  d.get('support_whatsapp', ''),
            'support_email':     d.get('support_email', ''),
        }
    except Exception:
        return {
            'platform_logo': '', 'platform_name': 'Estroid Gold ERP',
            'platform_tagline': 'Smart ERP System for Gold Factories',
            'platform_version': 'v5.0', 'support_whatsapp': '', 'support_email': '',
        }
import models.product_inventory  # registers ProductInventory table with db.create_all()

# ── Translation dictionaries ──────────────────────────────────────────────────

TRANSLATIONS = {
    'ar': {
        'dashboard': 'لوحة التحكم',
        'work_orders': 'أوامر العمل',
        'new_order': 'أمر جديد',
        'workers': 'الموظفين',
        'inventory': 'المخزون',
        'reports': 'التقارير',
        'logout': 'تسجيل الخروج',
        'admin_panel': 'لوحة الإدارة',
        'settings': 'الإعدادات',
        'login': 'تسجيل الدخول',
        'register': 'إنشاء حساب',
        'email': 'البريد الإلكتروني',
        'password': 'كلمة المرور',
        'confirm_password': 'تأكيد كلمة المرور',
        'factory_name': 'اسم المصنع',
        'full_name': 'الاسم الكامل',
        'city': 'المدينة',
        'phone': 'رقم الجوال',
        'sign_in': 'دخول',
        'create_account': 'إنشاء الحساب',
        'already_have_account': 'لديك حساب؟',
        'no_account': 'مصنع جديد؟',
        'total_gold': 'رصيد الذهب',
        'total_loss': 'إجمالي الفاقد',
        'active_orders': 'أوامر نشطة',
        'total_workers': 'عدد العمال',
        'completed_orders': 'أوامر مكتملة',
        'monthly_salary': 'الرواتب الشهرية',
        'recent_orders': 'آخر الأوامر',
        'inventory_movements': 'حركات المخزون',
        'gold_balance': 'رصيد الذهب',
        'grams': 'جرام (g)',
        'sar': 'ر.س',
        'order_number': 'رقم الأمر',
        'model_name': 'الموديل',
        'customer': 'العميل',
        'karat': 'العيار',
        'initial_weight': 'الوزن الابتدائي',
        'status': 'الحالة',
        'date': 'التاريخ',
        'actions': 'إجراءات',
        'active': 'نشط',
        'completed': 'مكتمل',
        'cancelled': 'ملغى',
        'view': 'عرض',
        'edit': 'تعديل',
        'delete': 'حذف',
        'add_stage': 'إضافة مرحلة',
        'complete_order': 'إتمام الأمر',
        'create_order': 'إنشاء أمر',
        'save': 'حفظ',
        'cancel': 'إلغاء',
        'back': 'رجوع',
        'notes': 'ملاحظات',
        'search': 'بحث',
        'filter': 'تصفية',
        'all': 'الكل',
        'stage': 'المرحلة',
        'worker': 'العامل',
        'received_weight': 'وزن المناولة',
        'produced_weight': 'الوزن المنتج',
        'scrap_weight': 'رجيع الذهب',
        'loss': 'الفاقد',
        'gain': 'الكسب',
        'net_result': 'الصافي',
        'loss_pct': 'نسبة الفاقد',
        'handover': 'مناولة',
        'complete_stage': 'إتمام المرحلة',
        'in_progress': 'جاري',
        'stage_handover': 'مناولة المرحلة',
        'stage_completion': 'إتمام المرحلة',
        'stone_type': 'نوع الحجر',
        'stone_color': 'لون الحجر',
        'stone_weight_ct': 'وزن الحجر (ق)',
        'stone_weight_g': 'وزن الحجر (جم)',
        'returned_stone': 'أحجار مرتجعة',
        'stone_section': 'الأحجار',
        'ct_to_g': 'ق→جم',
        'add_movement': 'تسجيل حركة',
        'movement_type': 'نوع الحركة',
        'incoming': 'وارد',
        'outgoing': 'صادر',
        'weight': 'الوزن',
        'description': 'وصف مختصر',
        'trans_date': 'التاريخ',
        'salary': 'الراتب',
        'specialty': 'التخصص',
        'add_worker': 'إضافة موظف',
        'worker_performance': 'أداء العامل',
        'total_stages': 'إجمالي المراحل',
        'completed_stages': 'مكتملة',
        'loss_report': 'تقرير الفاقد',
        'per_stage': 'حسب المرحلة',
        'per_worker': 'حسب الموظف',
        'per_order': 'حسب الأمر',
        'print': 'طباعة',
        'total': 'الإجمالي',
        'factories': 'المصانع',
        'new_factory': 'مصنع جديد',
        'activate': 'تفعيل',
        'deactivate': 'تعطيل',
        'plan': 'الباقة',
        'expiry': 'الانتهاء',
        'subscription': 'الاشتراك',
        'confirm_delete': 'تأكيد الحذف',
        'are_you_sure': 'هل أنت متأكد؟',
        'confirm': 'تأكيد',
        'warning': 'تحذير',
        'loss_warning': 'الفاقد يتجاوز 2%!',
        'gold_factory': 'نظام مصنع الذهب',
        'platform_name': 'منصة مصنع الذهب',
        'from_stone': 'من الأحجار',
        'stone_unit': 'وحدة الحجر',
        'stone_required': 'الكمية المطلوبة',
        'stone_given': 'المسلَّم',
        'stone_returned': 'المرتجع',
        'stone_used': 'المستهلك',
        'country_code': 'كود الدولة',
        'phone_number': 'رقم الجوال',
        'otp_code': 'كود التحقق',
        'verify_phone': 'التحقق من الجوال',
        'resend_otp': 'إعادة الإرسال',
        'err_phone_required': 'رقم الجوال مطلوب.',
        'err_code_required': 'كود التفعيل مطلوب.',
        'err_code_invalid': 'كود غير صحيح.',
        'err_code_used': 'الكود مستخدم.',
        'factory_settings': 'بيانات المصنع',
        'account_settings': 'الحساب',
        'subscription_settings': 'الاشتراك',
        'change_password': 'تغيير كلمة المرور',
        'factory_logo': 'شعار المصنع',
        'activation_code': 'كود التفعيل',
        'customers': 'العملاء',
        'add_customer': 'إضافة عميل',
        'customer_type': 'النوع',
        'client': 'عميل',
        'supplier': 'مورد',
        'customer_name': 'اسم العميل',
        'product_name': 'اسم المنتج',
        'product_code': 'كود المنتج',
        'exports': 'المبيعات والتصدير',
        'new_export': 'تصدير جديد',
        'new_import': 'وارد جديد',
        'labor_per_gram': 'أجرة الجرام',
        'labor_total': 'إجمالي الأجرة',
        'price_per_gram': 'سعر الجرام',
        'total_price': 'الإجمالي',
        'export_gold': 'تصدير ذهب',
        'import_gold': 'استيراد ذهب',
        'production_report': 'تقرير الإنتاج',
        'inventory_report': 'تقرير المخزون',
        'customers_report': 'تقرير العملاء',
        'total_produced': 'إجمالي المنتج',
        'total_in': 'إجمالي الوارد',
        'total_out': 'إجمالي الصادر',
        'current_balance': 'الرصيد الحالي',
        'pure_weight': 'الوزن الخالص (24K)',
        'pure_balance': 'رصيد الذهب الخالص',
        'pure_in': 'وارد خالص',
        'pure_out': 'صادر خالص',
        'total_pure_gold': 'إجمالي الذهب الخالص',
        'karat_label': 'العيار',
        'pure_formula': 'الوزن الخالص = الوزن × (العيار ÷ 24)',
        'subscription_expiry': 'تاريخ انتهاء الاشتراك',
        'subscription_status': 'حالة الاشتراك',
        'days_remaining': 'الأيام المتبقية',
        'gen_code': 'توليد كود جديد',
        'extend_subscription': 'تمديد الاشتراك',
        'extend_days': 'عدد الأيام',
        'set_expiry': 'تعيين الانتهاء',
        'sub_active': 'نشط',
        'sub_expired': 'منتهي',
        'sub_suspended': 'موقوف',
        'manage_subscription': 'إدارة الاشتراك',
        'reset_password': 'إعادة تعيين كلمة المرور',
        'new_password': 'كلمة المرور الجديدة',
        'err_invalid_credentials': 'البريد أو كلمة المرور غير صحيحة.',
        'err_account_deactivated': 'الحساب معطّل.',
        'err_suspended': 'المصنع موقوف.',
        'err_expired': 'انتهى الاشتراك.',
        'err_weight_positive': 'الوزن يجب أن يكون أكبر من صفر.',
        'msg_movement_saved': 'تم التسجيل.',
        'msg_deleted': 'تم الحذف.',
        'msg_settings_saved': 'تم الحفظ.',
        'activated': 'مفعّل',
        'deactivated': 'معطّل',
        'expired_factories': 'اشتراكات منتهية',
        'sub_expiry_date': 'تاريخ الانتهاء',
        'never': 'غير محدد',
        'day': 'يوم',
        'days': 'أيام',
        'employees': 'الموظفين',
        'employee_code': 'كود الموظف',
        'employee_name': 'اسم الموظف',
        'employee_role': 'المهنة',
        'employee_salary': 'الراتب الشهري',
        'employee_phone': 'الجوال',
        'employee_add': 'إضافة موظف',
        'employee_list': 'قائمة الموظفين',
        'employee_analysis': 'تحليل الموظفين',
        'employee_terminated': 'الموظفون السابقون',
        'employee_terminate': 'إنهاء الخدمة',
        'employee_id_card': 'طباعة البطاقة',
        'employee_status_active': 'نشط',
        'employee_status_off': 'منتهي الخدمة',
        'employee_dob': 'تاريخ الميلاد',
        'employee_age': 'العمر',
        'employee_id_number': 'رقم الهوية',
        'employee_id_expiry': 'انتهاء الهوية',
        'employee_nationality': 'الجنسية',
        'termination_date': 'تاريخ الإنهاء',
        'termination_notes': 'ملاحظات الإنهاء',
        'salary_due': 'مستحق الراتب',
        'worked_days': 'أيام العمل',
        'efficiency': 'الكفاءة',
        'loss_pct_label': 'نسبة الفاقد',
        'total_received': 'إجمالي المستلم',
        'total_produced_label': 'إجمالي المنتج',
        'total_loss_label': 'إجمالي الفاقد',
        'karat_analysis': 'تحليل حسب العيار',
        'production_stages': 'مراحل الإنتاج',
        'net_24k': 'صافي 24K',
        'customer_code': 'كود العميل',
        'customer_list': 'كشف العملاء',
        'customer_analysis': 'تحليل العملاء',
        'customer_profile': 'ملف العميل',
        'statement': 'كشف الحساب',
        'returns': 'الرجيع',
        'return_add': 'تسجيل رجيع',
        'allowed_return': 'المتاح للرجيع',
        'balance': 'الرصيد',
        'debtor': 'مدين',
        'creditor': 'دائن',
        'balanced': 'متوازن',
        'total_sent': 'إجمالي الصادر',
        'total_recv': 'إجمالي الوارد',
        'total_ret': 'إجمالي الرجيع',
        'last_transaction': 'آخر معاملة',
        'products': 'المنتجات',
        'product_inventory': 'مخزون المنتجات',
        'product_add': 'إضافة منتج',
        'product_analysis': 'تحليل المنتجات',
        'unit_weight': 'وزن الوحدة',
        'total_weight': 'الوزن الإجمالي',
        'quantity': 'الكمية',
        'input_mode_unit': 'وحدة',
        'input_mode_bulk': 'إجمالي',
        'input_mode_single': 'قطعة',
        'sales': 'المبيعات',
        'purchases': 'المشتريات',
        'new_sale': 'بيع جديد',
        'new_purchase': 'شراء جديد',
        'sale_list': 'كشف المبيعات',
        'purchase_list': 'كشف المشتريات',
        'sale_type_product': 'منتج جاهز',
        'sale_type_gold': 'ذهب مباشر',
        'operation_code': 'رقم العملية',
        'total_value': 'إجمالي القيمة',
        'ref_sale': 'عملية البيع المرجعية',
        'reports_products': 'تقرير المنتجات',
        'reports_purchases': 'تقرير المشتريات',
        'reports_sales': 'تقرير المبيعات',
        'reports_archive': 'الأرشيف',
        'archive_new': 'أرشفة جديدة',
        'archive_label': 'عنوان الأرشيف',
        'archive_from': 'من تاريخ',
        'archive_to': 'إلى تاريخ',
        'archive_confirm_pw': 'كلمة المرور للتأكيد',
        'archive_save': 'حفظ الأرشيف',
        'archive_view': 'عرض',
        'date_from': 'من',
        'date_to': 'إلى',
        'upload_logo': 'رفع شعار المصنع',
        'remove_logo': 'حذف الشعار',
        'logo_size_limit': 'الحد 500KB',
        'language': 'English',
        'language_tr': 'Türkçe',
        'dir': 'rtl',
        'active_label': 'نشط',
        'inactive_label': 'غير نشط',
        'terminated_label': 'منتهي الخدمة',
        'expired_label': 'منتهية',
        'id_expired_badge': 'هوية منتهية',
        'private_label': 'خاصة',
        'balanced_label': 'متوازن',
        'add_to_inventory': 'إضافة للمخزون',
        'print_card': 'طباعة البطاقة',
        'terminate_service': 'إنهاء الخدمة',
        'close_modal': 'إغلاق',
        'archive_btn': 'أرشفة',
        'save_archive_btn': 'حفظ الأرشيف',
        'new_sale_btn': 'بيع جديد',
        'new_purchase_btn': 'شراء جديد',
        'register_sale': 'تسجيل البيع',
        'register_purchase': 'تسجيل الشراء',
        'invoice_btn': 'فاتورة',
        'invoice_sale': 'فاتورة بيع',
        'invoice_purchase': 'فاتورة شراء',
        'upload_logo_btn': 'رفع الشعار',
        'remove_logo_btn': 'حذف الشعار',
        'open_order': 'فتح الأمر',
        'back_to_order': 'الرجوع للأمر',
        'end_edit': 'إنهاء التعديل',
        'employee_active_list': 'الموظفون النشطون',
        'customers_list_label': 'قائمة العملاء',
        'employee_list_label': 'قائمة الموظفين',
        'customers_statement': 'كشف العملاء',
        'sales_statement': 'كشف المبيعات',
        'purchases_statement': 'كشف المشتريات',
        'settlement_summary': 'ملخص المستحقات',
        'personal_info': 'المعلومات الشخصية',
        'inventory_board': 'لوحة المخزون',
        'gold_movements': 'حركة الذهب',
        'product_stock': 'مخزون المنتجات',
        'product_analysis_nav': 'تحليل المنتجات',
        'customer_analysis_nav': 'تحليل العملاء',
        'employee_analysis_nav': 'تحليل الموظفين',
        'add_employee_nav': 'إضافة موظف',
        'add_customer_nav': 'إضافة عميل',
        'add_product_nav': 'إضافة منتج',
        'top_production': 'أعلى إنتاجاً',
        'lowest_loss': 'أقل فاقداً',
        'most_operations': 'أكثر عمليات',
        'top_by_sales': 'أعلى 5 عملاء بالمبيعات',
        'highest_debtors': 'أعلى 5 أرصدة مدينة',
        'password_confirm_label': 'كلمة المرور *',
        'confirm_terminate': 'تأكيد إنهاء الخدمة',
        'from_work_order': 'من أمر تشغيل',
        'to_work_order': 'إلى أمر تشغيل',
        'from_products': 'من المنتجات',
        'from_customer': 'من عميل',
        'to_customer': 'إلى عميل',
        'print_btn': 'طباعة',
        'archive_period': 'أرشفة الفترة',
        'new_archive_btn': 'أرشفة جديدة',
        'currently_active': 'نشط',
        'in_progress_badge': 'قيد التنفيذ',
        'completed_badge': 'مكتمل',
        'cancelled_badge': 'ملغى',
        'debtor_badge': 'مدين',
        'creditor_badge': 'دائن',
        'op_code': 'رقم العملية',
        'sale_type': 'نوع المعاملة',
        'transaction_date': 'تاريخ المعاملة',
        'total_products': 'عدد المنتجات',
        'total_ops': 'عدد العمليات',
        'today_ops': 'عمليات اليوم',
        'registered_workers': 'الموظفون المسجلون',
        'total_customers': 'إجمالي العملاء',
        'all_orders': 'إجمالي الأوامر',
        'best_worker_label': 'أفضل موظف (أقل فاقد)',
        'worst_stage_label': 'أعلى مرحلة فاقداً',
        'top_client_label': 'أكثر عميل تعاملاً',
        'sales_and_purchases': 'مبيعات + مشتريات',
        'today': 'اليوم',
        'in_inventory': 'في المخزون',
        'no_data': 'لا توجد بيانات بعد',
        'total_production_label': 'إجمالي الإنتاج (24K)',
        'total_scrap_label': 'إجمالي رجيع الذهب (24K)',
        'employees_count': 'عدد الموظفين',
        'customers_count': 'عدد العملاء',
        'add_factory': '+ إضافة مصنع',
        'alerts': 'التنبيهات',
        'completion_pct': 'نسبة الإنجاز',
        'expiring_soon': 'تنتهي خلال 7 أيام',
        'inactive_factories': 'مصانع غير نشطة',
        'more': 'أخرى',
        'factory_code_label': 'كود المصنع',
        'factory_code_new': 'كود جديد',
        'copy': 'نسخ',
        'system_team': 'فريق النظام',
        'system_team_desc': 'موظفو إدارة المنصة — مستقل عن المصانع',
        'add_team_member': '+ إضافة موظف نظام',
        'team_member_info': 'بيانات الموظف',
        'team_note': 'سيتم توليد كود موظف تلقائياً (EMP-XXXX)',
        'system_role_label': 'الدور الوظيفي',
        'role_support': 'دعم فني',
        'role_accountant': 'محاسبة',
        'role_manager': 'مدير',
        'no_team_members': 'لا يوجد موظفون بعد',
        'factory_users': 'مستخدمو المصانع',
        'factory_users_desc': 'أصحاب المصانع المسجلين في المنصة',
        'last_login': 'آخر تسجيل دخول',
        'total_factories_label': 'إجمالي المصانع',
        'active_factories_label': 'مصانع نشطة',
        'total_orders_label': 'إجمالي الأوامر',
        'platform_activity': 'نشاط المنصة',
        'subscriptions': 'إدارة الاشتراكات',
        'unlimited_subs': 'اشتراكات غير محدودة',
        'expiring_30': 'تنتهي خلال 30 يوم',
        'across_all_factories': 'في جميع المصانع',
        'quick_links': 'روابط سريعة',
        'staff_limited_access': 'بعض الإجراءات محدودة لصلاحيتك',
        'is_active': 'الحالة',
        'slot_desc': 'أنشئ كود تفعيل وشاركه مع المصنع للتسجيل في /auth/register',
        'generate_code': 'توليد كود جديد',
        'total_codes': 'إجمالي الأكواد',
        'unused_codes': 'غير مستخدمة',
        'used_codes': 'مستخدمة',
        'disabled_codes': 'معطلة',
        'optional': 'اختياري',
        'print_preview': 'معاينة الطباعة',
        'generate_to_preview': 'ولّد كوداً لرؤية المعاينة',
        'all_codes': 'جميع الأكواد',
        'no_codes_yet': 'لا توجد أكواد بعد',
        'register_at': 'التسجيل عبر',
        'pending': 'معلق',
        'contact_support': 'تواصل مع خدمة العملاء',
        'whatsapp_msg': 'السلام عليكم، عندي استفسار بخصوص نظام مصنع الذهب',
        'platform_settings': 'إعدادات المنصة',
        'platform_settings_desc': 'هوية المنصة وبيانات التواصل',
        'whatsapp_settings': 'إعدادات واتساب',
        'support_whatsapp_label': 'رقم خدمة العملاء (واتساب)',
        'whatsapp_note': 'أدخل الرقم بصيغة دولية مثل: +966501234567',
        'test_link': 'اختبار الرابط',
        'preview': 'معاينة الرابط',
        'print_footer_note': 'تم إنشاء هذا التقرير بواسطة نظام مصنع الذهب',
        'thank_you': 'شكراً لتعاملكم معنا',
        'invoice_date': 'تاريخ الفاتورة',
        'platform_identity': 'هوية المنصة',
        'platform_name_label': 'اسم المنصة',
        'platform_tagline_label': 'الشعار / Tagline',
        'platform_version_label': 'الإصدار',
        'contact_settings': 'بيانات التواصل',
        'support_email_label': 'إيميل الدعم الفني',
        'forgot_password': 'نسيت كلمة المرور؟',
        'forgot_password_desc': 'أدخل بريدك الإلكتروني ورقم جوالك للتحقق',
        'verify_identity': 'التحقق من الهوية',
        'verify_both_required': 'يجب أن يتطابق الإيميل والجوال معاً',
        'back_to_login': 'العودة لتسجيل الدخول',
        'need_help': 'تحتاج مساعدة؟',
        'save_password': 'حفظ كلمة المرور',
        'session_expires_note': 'هذه الجلسة تنتهي خلال 15 دقيقة',
        'password_updated': 'تم تحديث كلمة المرور بنجاح. يمكنك تسجيل الدخول.',
        'err_reset_mismatch': 'البيانات غير مطابقة — تأكد من الإيميل ورقم الجوال.',
        'err_rate_limit': 'محاولات كثيرة — انتظر 15 دقيقة وأعد المحاولة.',
        'err_session_expired': 'انتهت صلاحية الجلسة — أعد طلب الاستعادة.',
        'err_password_short': 'كلمة المرور يجب أن تكون 8 أحرف على الأقل.',
        'err_password_mismatch': 'كلمتا المرور غير متطابقتين.',
        'passwords_match': '✓ كلمتا المرور متطابقتان',
        'pw_weak': 'ضعيفة',
        'pw_fair': 'مقبولة',
        'pw_good': 'جيدة',
        'pw_strong': 'قوية ✓',
        'total_revenue': 'إجمالي الإيرادات',
        'month_revenue': 'إيرادات هذا الشهر',
        'active_subs': 'اشتراكات نشطة',
        'expired_subs': 'اشتراكات منتهية',
        'total_payments': 'إجمالي الدفعات',
        'payment_history': 'سجل المدفوعات',
        'add_payment': 'تسجيل دفعة',
        'payment_recorded': 'تم تسجيل الدفعة',
        'payment_method': 'طريقة الدفع',
        'payment_status': 'حالة الدفع',
        'payment_note': 'سيتم تمديد اشتراك المصنع تلقائياً بعد التسجيل.',
        'record_payment': 'تسجيل الدفعة',
        'bank_transfer': 'تحويل بنكي',
        'cash': 'نقدي',
        'manual': 'يدوي',
        'paid': 'مدفوع',
        'refunded': 'مسترجع',
        'failed': 'فشل',
        'invoice_no': 'رقم الفاتورة',
        'all_payments': 'جميع الدفعات',
        'no_payments_yet': 'لا توجد دفعات بعد',
        'recorded_by': 'سجّل بواسطة',
        'amount': 'المبلغ',
        'period': 'المدة',
        'currency': 'العملة',
        'plans': 'الباقات',
        'plan_name': 'اسم الباقة',
        'price_month': 'سعر/شهر',
        'price_year': 'سعر/سنة',
        'month': 'شهر',
        'year': 'سنة',
        'health_score': 'صحة الحساب',
        'factory_notes': 'ملاحظات داخلية',
        'add_note': 'أضف ملاحظة...',
        'no_notes': 'لا توجد ملاحظات بعد',
        'note_general': 'عام',
        'note_payment': 'دفع',
        'note_contacted': 'تم التواصل',
        'note_discount': 'خصم',
        'note_issue': 'مشكلة',
        'select': 'اختر',
        'analytics': 'التحليلات',
        'monthly_revenue': 'الإيرادات الشهرية',
        'avg_sub_value': 'متوسط قيمة الاشتراك',
        'top_payers': 'أكثر المصانع دفعاً',
        'recalc_health': 'تحديث مؤشر الصحة',
        'err_read_only': 'حسابك في وضع القراءة فقط — اشتراكك انتهى. تواصل مع الإدارة.',
        'err_grace_period': '⚠️ الاشتراك انتهى — فترة السماح نشطة. جدد الاشتراك قريباً.',
        'tab_general': 'عام',
        'tab_identity': 'الهوية',
        'tab_invoice': 'الفواتير',
        'tab_system': 'النظام',
        'tab_security': 'الأمان',
        'tab_subscription': 'الاشتراك',
        'tab_support': 'الدعم',
        'factory_info': 'معلومات المصنع',
        'contact_info': 'معلومات التواصل',
        'country': 'الدولة',
        'address': 'العنوان',
        'commercial_reg': 'السجل التجاري',
        'tax_number': 'الرقم الضريبي',
        'whatsapp': 'واتساب',
        'website': 'الموقع الإلكتروني',
        'brand_identity': 'الهوية البصرية',
        'logo_saved': 'تم حفظ الشعار ✓',
        'logo_removed': 'تم حذف الشعار.',
        'invoice_settings': 'إعدادات الفواتير',
        'thank_you_msg': 'عبارة الشكر في الفاتورة',
        'invoice_footer': 'تذييل الفاتورة',
        'appears_in_invoice': 'تظهر أسفل كل فاتورة',
        'system_settings': 'إعدادات النظام',
        'default_karat': 'العيار الافتراضي',
        'weight_unit': 'وحدة الوزن',
        'ounce': 'أونصة (oz)',
        'change_email': 'تغيير الإيميل',
        'change_email_note': 'تغيير الإيميل يتطلب تأكيد كلمة المرور.',
        'current_email': 'الإيميل الحالي',
        'new_email': 'الإيميل الجديد',
        'verify_password': 'كلمة المرور للتأكيد',
        'update_email': 'تحديث الإيميل',
        'email_updated': 'تم تحديث الإيميل ✓',
        'email_taken': 'هذا الإيميل مستخدم من حساب آخر.',
        'email_required': 'الإيميل مطلوب.',
        'settings_saved': 'تم الحفظ ✓',
        'need_renewal': 'لتجديد الاشتراك تواصل مع فريق الدعم',
        'renew_via_whatsapp': 'تجديد عبر واتساب',
        'renewal_msg': 'أريد تجديد اشتراك نظام مصنع الذهب',
        'tech_support': 'الدعم الفني',
        'backup_restore': 'النسخ الاحتياطي',
        'backup_note': 'النسخة تشمل: الموظفين، العملاء، أوامر العمل.',
        'create_backup': 'تحميل نسخة احتياطية',
        'change_in_security': 'غيّر الإيميل من تبويب الأمان',
        'err_wrong_password': 'كلمة المرور الحالية غير صحيحة.',
        'last_login_ip': 'آخر IP',
        'session_activity': 'النشاط والجلسات',
        'logout_all_devices': 'تسجيل الخروج من جميع الأجهزة',
        'logged_out_all': 'تم تسجيل الخروج من جميع الأجهزة.',
        'confirm_logout_all': 'هل تريد تسجيل الخروج من جميع الأجهزة؟',
        'api_key': 'API Key',
        'api_key_note': 'احتفظ بهذا المفتاح آمناً — لا تشاركه مع أحد.',
        'no_api_key': 'لا يوجد API Key — أنشئ واحداً',
        'gen_api_key': 'إنشاء API Key',
        'api_key_generated': 'تم إنشاء API Key جديد ✓',
        'confirm_regen_api': 'إعادة الإنشاء ستلغي المفتاح القديم. هل تريد المتابعة؟',
        'report_issue': 'الإبلاغ عن مشكلة',
        'issue_desc': 'وصف المشكلة',
        'issue_placeholder': 'اكتب وصفاً دقيقاً للمشكلة...',
        'send_report': 'إرسال البلاغ',
        'issue_reported': 'تم إرسال البلاغ ✓ — سيتواصل معك فريق الدعم.',
        'factory_qr': 'QR المصنع وبيانات النظام',
        'download_qr': 'تحميل QR',
        'server_status': 'حالة السيرفر',
        'online': 'متصل',
        'factory_color': 'لون المصنع',
        'color_note': 'يُستخدم في الطباعة والهوية',
        'restore_backup': 'استعادة نسخة احتياطية',
        'restore_warning': 'تحذير: الاستعادة ستستبدل البيانات الحالية.',
        'select_backup_file': 'اختر ملف النسخة الاحتياطية',
        'coming_soon': 'قريباً — سيتم تفعيلها في الإصدار القادم',
        'account_since': 'عضو منذ',
        'toggle_mode': 'تبديل الوضع المضيء/الداكن',
        'registered_phone': 'رقم الجوال المسجل',
        'change_in_general': 'غيّر من تبويب عام',
        'not_set': 'غير محدد',
    },
    'en': {
        'dashboard': 'Dashboard',
        'work_orders': 'Work Orders',
        'new_order': 'New Order',
        'workers': 'Workers',
        'inventory': 'Inventory',
        'reports': 'Reports',
        'logout': 'Logout',
        'admin_panel': 'Admin Panel',
        'settings': 'Settings',
        'login': 'Login',
        'register': 'Register',
        'email': 'Email',
        'password': 'Password',
        'confirm_password': 'Confirm Password',
        'factory_name': 'Factory Name',
        'full_name': 'Full Name',
        'city': 'City',
        'phone': 'Phone',
        'sign_in': 'Sign In',
        'create_account': 'Create Account',
        'already_have_account': 'Already have an account?',
        'no_account': 'New factory?',
        'total_gold': 'Gold Balance',
        'total_loss': 'Total Loss',
        'active_orders': 'Active Orders',
        'total_workers': 'Total Workers',
        'completed_orders': 'Completed Orders',
        'monthly_salary': 'Monthly Salaries',
        'recent_orders': 'Recent Orders',
        'inventory_movements': 'Inventory Movements',
        'gold_balance': 'Gold Balance',
        'grams': 'Gram (g)',
        'sar': 'SAR',
        'order_number': 'Order No.',
        'model_name': 'Model',
        'customer': 'Customer',
        'karat': 'Karat',
        'initial_weight': 'Initial Weight',
        'status': 'Status',
        'date': 'Date',
        'actions': 'Actions',
        'active': 'Active',
        'completed': 'Completed',
        'cancelled': 'Cancelled',
        'view': 'View',
        'edit': 'Edit',
        'delete': 'Delete',
        'add_stage': 'Add Stage',
        'complete_order': 'Complete Order',
        'create_order': 'Create Order',
        'save': 'Save',
        'cancel': 'Cancel',
        'back': 'Back',
        'notes': 'Notes',
        'search': 'Search',
        'filter': 'Filter',
        'all': 'All',
        'stage': 'Stage',
        'worker': 'Worker',
        'received_weight': 'Received Weight',
        'produced_weight': 'Produced Weight',
        'scrap_weight': 'Scrap Weight',
        'loss': 'Loss',
        'gain': 'Gain',
        'net_result': 'Net Result',
        'loss_pct': 'Loss %',
        'handover': 'Handover',
        'complete_stage': 'Complete Stage',
        'in_progress': 'In Progress',
        'stage_handover': 'Stage Handover',
        'stage_completion': 'Stage Completion',
        'stone_type': 'Stone Type',
        'stone_color': 'Stone Color',
        'stone_weight_ct': 'Stone Weight (ct)',
        'stone_weight_g': 'Stone Weight (g)',
        'returned_stone': 'Returned Stones',
        'stone_section': 'Stones',
        'ct_to_g': 'ct → g',
        'add_movement': 'Add Movement',
        'movement_type': 'Movement Type',
        'incoming': 'Incoming',
        'outgoing': 'Outgoing',
        'weight': 'Weight',
        'description': 'Short Description',
        'trans_date': 'Date',
        'salary': 'Salary',
        'specialty': 'Specialty',
        'add_worker': 'Add Worker',
        'worker_performance': 'Worker Performance',
        'total_stages': 'Total Stages',
        'completed_stages': 'Completed',
        'loss_report': 'Loss Report',
        'per_stage': 'By Stage',
        'per_worker': 'By Worker',
        'per_order': 'By Order',
        'print': 'Print',
        'total': 'Total',
        'factories': 'Factories',
        'new_factory': 'New Factory',
        'activate': 'Activate',
        'deactivate': 'Deactivate',
        'plan': 'Plan',
        'expiry': 'Expiry',
        'subscription': 'Subscription',
        'confirm_delete': 'Confirm Delete',
        'are_you_sure': 'Are you sure?',
        'confirm': 'Confirm',
        'warning': 'Warning',
        'loss_warning': 'Loss exceeds 2%!',
        'gold_factory': 'Gold Factory System',
        'platform_name': 'Gold Factory Platform',
        'from_stone': 'From Stones',
        'stone_unit': 'Stone Unit',
        'stone_required': 'Required Quantity',
        'stone_given': 'Given to Worker',
        'stone_returned': 'Returned Stones',
        'stone_used': 'Stone Used',
        'country_code': 'Country Code',
        'phone_number': 'Phone Number',
        'otp_code': 'OTP Code',
        'verify_phone': 'Verify Phone',
        'resend_otp': 'Resend OTP',
        'err_phone_required': 'Phone number is required.',
        'err_code_required': 'Activation code required.',
        'err_code_invalid': 'Invalid code.',
        'err_code_used': 'Code already used.',
        'factory_settings': 'Factory Details',
        'account_settings': 'Account',
        'subscription_settings': 'Subscription',
        'change_password': 'Change Password',
        'factory_logo': 'Factory Logo',
        'activation_code': 'Activation Code',
        'customers': 'Customers',
        'add_customer': 'Add Customer',
        'customer_type': 'Type',
        'client': 'Client',
        'supplier': 'Supplier',
        'customer_name': 'Customer Name',
        'product_name': 'Product Name',
        'product_code': 'Product Code',
        'exports': 'Sales & Exports',
        'new_export': 'New Export',
        'new_import': 'New Import',
        'labor_per_gram': 'Labor/Gram',
        'labor_total': 'Total Labor',
        'price_per_gram': 'Price/g',
        'total_price': 'Total',
        'export_gold': 'Export Gold',
        'import_gold': 'Import Gold',
        'production_report': 'Production Report',
        'inventory_report': 'Inventory Report',
        'customers_report': 'Customers Report',
        'total_produced': 'Total Gold Produced',
        'total_in': 'Total In',
        'total_out': 'Total Out',
        'current_balance': 'Current Balance',
        'pure_weight': 'Pure Weight (24K)',
        'pure_balance': 'Pure Gold Balance',
        'pure_in': 'Pure In',
        'pure_out': 'Pure Out',
        'total_pure_gold': 'Total Pure Gold (24K)',
        'karat_label': 'Karat',
        'pure_formula': 'Pure = Weight × (Karat ÷ 24)',
        'subscription_expiry': 'Subscription Expiry',
        'subscription_status': 'Subscription Status',
        'days_remaining': 'Days Remaining',
        'gen_code': 'Generate New Code',
        'extend_subscription': 'Extend Subscription',
        'extend_days': 'Days',
        'set_expiry': 'Set Expiry',
        'sub_active': 'Active',
        'sub_expired': 'Expired',
        'sub_suspended': 'Suspended',
        'manage_subscription': 'Manage Subscription',
        'reset_password': 'Reset Password',
        'new_password': 'New Password',
        'err_invalid_credentials': 'Invalid email or password.',
        'err_account_deactivated': 'Account deactivated.',
        'err_suspended': 'Factory suspended.',
        'err_expired': 'Subscription expired.',
        'err_weight_positive': 'Weight must be positive.',
        'msg_movement_saved': 'Movement recorded.',
        'msg_deleted': 'Deleted.',
        'msg_settings_saved': 'Settings saved.',
        'activated': 'Activated',
        'deactivated': 'Deactivated',
        'expired_factories': 'Expired Subscriptions',
        'sub_expiry_date': 'Expiry Date',
        'never': 'No Expiry',
        'day': 'day',
        'days': 'days',
        'employees': 'Employees',
        'employee_code': 'Employee Code',
        'employee_name': 'Employee Name',
        'employee_role': 'Role / Specialty',
        'employee_salary': 'Monthly Salary',
        'employee_phone': 'Phone',
        'employee_add': 'Add Employee',
        'employee_list': 'Employee List',
        'employee_analysis': 'Employee Analysis',
        'employee_terminated': 'Former Employees',
        'employee_terminate': 'Terminate',
        'employee_id_card': 'Print ID Card',
        'employee_status_active': 'Active',
        'employee_status_off': 'Terminated',
        'employee_dob': 'Date of Birth',
        'employee_age': 'Age',
        'employee_id_number': 'ID / Iqama No.',
        'employee_id_expiry': 'ID Expiry Date',
        'employee_nationality': 'Nationality',
        'termination_date': 'Termination Date',
        'termination_notes': 'Termination Notes',
        'salary_due': 'Salary Due',
        'worked_days': 'Days Worked',
        'efficiency': 'Efficiency',
        'loss_pct_label': 'Loss %',
        'total_received': 'Total Received',
        'total_produced_label': 'Total Produced',
        'total_loss_label': 'Total Loss',
        'karat_analysis': 'Karat Breakdown',
        'production_stages': 'Production Stages',
        'net_24k': 'Net 24K',
        'customer_code': 'Customer Code',
        'customer_list': 'Customer List',
        'customer_analysis': 'Customer Analysis',
        'customer_profile': 'Customer Profile',
        'statement': 'Statement',
        'returns': 'Returns',
        'return_add': 'Add Return',
        'allowed_return': 'Returnable Weight',
        'balance': 'Balance',
        'debtor': 'Debtor',
        'creditor': 'Creditor',
        'balanced': 'Balanced',
        'total_sent': 'Total Sent',
        'total_recv': 'Total Received',
        'total_ret': 'Total Returns',
        'last_transaction': 'Last Transaction',
        'products': 'Products',
        'product_inventory': 'Product Inventory',
        'product_add': 'Add Product',
        'product_analysis': 'Product Analysis',
        'unit_weight': 'Unit Weight',
        'total_weight': 'Total Weight',
        'quantity': 'Quantity',
        'input_mode_unit': 'Per Unit',
        'input_mode_bulk': 'Bulk',
        'input_mode_single': 'Single',
        'sales': 'Sales',
        'purchases': 'Purchases',
        'new_sale': 'New Sale',
        'new_purchase': 'New Purchase',
        'sale_list': 'Sales List',
        'purchase_list': 'Purchases List',
        'sale_type_product': 'Finished Product',
        'sale_type_gold': 'Raw Gold',
        'operation_code': 'Operation Code',
        'total_value': 'Total Value',
        'ref_sale': 'Referenced Sale',
        'reports_products': 'Products Report',
        'reports_purchases': 'Purchases Report',
        'reports_sales': 'Sales Report',
        'reports_archive': 'Archive',
        'archive_new': 'New Archive',
        'archive_label': 'Archive Title',
        'archive_from': 'From Date',
        'archive_to': 'To Date',
        'archive_confirm_pw': 'Password to Confirm',
        'archive_save': 'Save Archive',
        'archive_view': 'View',
        'date_from': 'From',
        'date_to': 'To',
        'upload_logo': 'Upload Factory Logo',
        'remove_logo': 'Remove Logo',
        'logo_size_limit': 'Max 500KB',
        'language': 'Language',
        'language_tr': 'Türkçe',
        'dir': 'ltr',
        'active_label': 'Active',
        'inactive_label': 'Inactive',
        'terminated_label': 'Terminated',
        'expired_label': 'Expired',
        'id_expired_badge': 'ID Expired',
        'private_label': 'Private',
        'balanced_label': 'Balanced',
        'add_to_inventory': 'Add to Inventory',
        'print_card': 'Print ID Card',
        'terminate_service': 'Terminate',
        'close_modal': 'Close',
        'archive_btn': 'Archive',
        'save_archive_btn': 'Save Archive',
        'new_sale_btn': 'New Sale',
        'new_purchase_btn': 'New Purchase',
        'register_sale': 'Register Sale',
        'register_purchase': 'Register Purchase',
        'invoice_btn': 'Invoice',
        'invoice_sale': 'Sale Invoice',
        'invoice_purchase': 'Purchase Invoice',
        'upload_logo_btn': 'Upload Logo',
        'remove_logo_btn': 'Remove Logo',
        'open_order': 'Open Order',
        'back_to_order': 'Back to Order',
        'end_edit': 'End Edit',
        'employee_active_list': 'Active Employees',
        'customers_list_label': 'Customer List',
        'employee_list_label': 'Employee List',
        'customers_statement': 'Customers Statement',
        'sales_statement': 'Sales Statement',
        'purchases_statement': 'Purchases Statement',
        'settlement_summary': 'Settlement Summary',
        'personal_info': 'Personal Info',
        'inventory_board': 'Inventory Board',
        'gold_movements': 'Gold Movements',
        'product_stock': 'Product Stock',
        'product_analysis_nav': 'Product Analysis',
        'customer_analysis_nav': 'Customer Analysis',
        'employee_analysis_nav': 'Employee Analysis',
        'add_employee_nav': 'Add Employee',
        'add_customer_nav': 'Add Customer',
        'add_product_nav': 'Add Product',
        'top_production': 'Top Production',
        'lowest_loss': 'Lowest Loss',
        'most_operations': 'Most Operations',
        'top_by_sales': 'Top 5 by Sales',
        'highest_debtors': 'Top 5 Debtors',
        'password_confirm_label': 'Password *',
        'confirm_terminate': 'Confirm Termination',
        'from_work_order': 'From Work Order',
        'to_work_order': 'To Work Order',
        'from_products': 'From Products',
        'from_customer': 'From Customer',
        'to_customer': 'To Customer',
        'print_btn': 'Print',
        'archive_period': 'Archive Period',
        'new_archive_btn': 'New Archive',
        'currently_active': 'Active',
        'in_progress_badge': 'In Progress',
        'completed_badge': 'Completed',
        'cancelled_badge': 'Cancelled',
        'debtor_badge': 'Debtor',
        'creditor_badge': 'Creditor',
        'op_code': 'Op. Code',
        'sale_type': 'Transaction Type',
        'transaction_date': 'Transaction Date',
        'total_products': 'Products',
        'total_ops': 'Operations',
        'today_ops': "Today's Ops",
        'registered_workers': 'Registered Employees',
        'total_customers': 'Total Customers',
        'all_orders': 'Total Orders',
        'best_worker_label': 'Best Worker (Least Loss)',
        'worst_stage_label': 'Highest Loss Stage',
        'top_client_label': 'Top Client',
        'sales_and_purchases': 'Sales + Purchases',
        'today': 'Today',
        'in_inventory': 'In Stock',
        'no_data': 'No data yet',
        'total_production_label': 'Total Production (24K)',
        'total_scrap_label': 'Total Gold Scrap (24K)',
        'employees_count': 'Employees',
        'customers_count': 'Customers',
        'add_factory': '+ Add Factory',
        'alerts': 'Alerts',
        'completion_pct': 'Completion Rate',
        'expiring_soon': 'Expiring in 7 days',
        'inactive_factories': 'Inactive Factories',
        'more': 'more',
        'factory_code_label': 'Factory Code',
        'factory_code_new': 'New Code',
        'copy': 'Copy',
        'system_team': 'System Team',
        'system_team_desc': 'Platform management staff — separate from factories',
        'add_team_member': '+ Add Staff Member',
        'team_member_info': 'Staff Details',
        'team_note': 'Employee code will be auto-generated (EMP-XXXX)',
        'system_role_label': 'Role',
        'role_support': 'Support',
        'role_accountant': 'Accountant',
        'role_manager': 'Manager',
        'no_team_members': 'No team members yet',
        'factory_users': 'Factory Users',
        'factory_users_desc': 'Factory owners registered on the platform',
        'last_login': 'Last Login',
        'total_factories_label': 'Total Factories',
        'active_factories_label': 'Active Factories',
        'total_orders_label': 'Total Orders',
        'platform_activity': 'Platform Activity',
        'subscriptions': 'Subscription Management',
        'unlimited_subs': 'Unlimited',
        'expiring_30': 'Expiring in 30 days',
        'across_all_factories': 'Across all factories',
        'quick_links': 'Quick Links',
        'staff_limited_access': 'Some actions are restricted based on your role',
        'is_active': 'Status',
        'slot_desc': 'Generate an activation code and share it with the factory to register at /auth/register',
        'generate_code': 'Generate New Code',
        'total_codes': 'Total Codes',
        'unused_codes': 'Unused',
        'used_codes': 'Used',
        'disabled_codes': 'Disabled',
        'optional': 'Optional',
        'print_preview': 'Print Preview',
        'generate_to_preview': 'Generate a code to see preview',
        'all_codes': 'All Codes',
        'no_codes_yet': 'No codes yet — start by generating one',
        'register_at': 'Register at',
        'pending': 'Pending',
        'contact_support': 'Contact Support',
        'whatsapp_msg': 'Hello, I have an inquiry about Gold Factory system',
        'platform_settings': 'Platform Settings',
        'platform_settings_desc': 'Platform identity and contact information',
        'whatsapp_settings': 'WhatsApp Settings',
        'support_whatsapp_label': 'Customer Support Number (WhatsApp)',
        'whatsapp_note': 'Enter international format e.g. +966501234567',
        'test_link': 'Test Link',
        'preview': 'Link Preview',
        'print_footer_note': 'Generated by Gold Factory System',
        'thank_you': 'Thank you for your business',
        'invoice_date': 'Invoice Date',
        'platform_identity': 'Platform Identity',
        'platform_name_label': 'Platform Name',
        'platform_tagline_label': 'Tagline',
        'platform_version_label': 'Version',
        'contact_settings': 'Contact Details',
        'support_email_label': 'Support Email',
        'forgot_password': 'Forgot Password?',
        'forgot_password_desc': 'Enter your email and phone number to verify your identity',
        'verify_identity': 'Verify Identity',
        'verify_both_required': 'Both email and phone must match your account',
        'back_to_login': 'Back to Login',
        'need_help': 'Need help?',
        'save_password': 'Save Password',
        'session_expires_note': 'This session expires in 15 minutes',
        'password_updated': 'Password updated successfully. You can now log in.',
        'err_reset_mismatch': 'Details do not match — check your email and phone number.',
        'err_rate_limit': 'Too many attempts — please wait 15 minutes.',
        'err_session_expired': 'Session expired — please request a new reset.',
        'err_password_short': 'Password must be at least 8 characters.',
        'err_password_mismatch': 'Passwords do not match.',
        'passwords_match': '✓ Passwords match',
        'pw_weak': 'Weak',
        'pw_fair': 'Fair',
        'pw_good': 'Good',
        'pw_strong': 'Strong ✓',
        'total_revenue': 'Total Revenue',
        'month_revenue': 'This Month Revenue',
        'active_subs': 'Active Subscriptions',
        'expired_subs': 'Expired Subscriptions',
        'total_payments': 'Total Payments',
        'payment_history': 'Payment History',
        'add_payment': 'Record Payment',
        'payment_recorded': 'Payment Recorded',
        'payment_method': 'Payment Method',
        'payment_status': 'Payment Status',
        'payment_note': 'Subscription will be extended automatically after recording.',
        'record_payment': 'Record Payment',
        'bank_transfer': 'Bank Transfer',
        'cash': 'Cash',
        'manual': 'Manual',
        'paid': 'Paid',
        'refunded': 'Refunded',
        'failed': 'Failed',
        'invoice_no': 'Invoice #',
        'all_payments': 'All Payments',
        'no_payments_yet': 'No payments yet',
        'recorded_by': 'Recorded By',
        'amount': 'Amount',
        'period': 'Period',
        'currency': 'Currency',
        'plans': 'Plans',
        'plan_name': 'Plan Name',
        'price_month': 'Price/Month',
        'price_year': 'Price/Year',
        'month': 'Month',
        'year': 'Year',
        'health_score': 'Health Score',
        'factory_notes': 'Internal Notes',
        'add_note': 'Add a note...',
        'no_notes': 'No notes yet',
        'note_general': 'General',
        'note_payment': 'Payment',
        'note_contacted': 'Contacted',
        'note_discount': 'Discount',
        'note_issue': 'Issue',
        'select': 'Select',
        'analytics': 'Analytics',
        'monthly_revenue': 'Monthly Revenue',
        'avg_sub_value': 'Average Subscription Value',
        'top_payers': 'Top Paying Factories',
        'recalc_health': 'Recalculate Health Scores',
        'err_read_only': 'Account is in Read-Only mode — subscription expired. Contact admin.',
        'err_grace_period': '⚠️ Subscription expired — grace period active. Please renew soon.',
        'tab_general': 'General',
        'tab_identity': 'Identity',
        'tab_invoice': 'Invoices',
        'tab_system': 'System',
        'tab_security': 'Security',
        'tab_subscription': 'Subscription',
        'tab_support': 'Support',
        'factory_info': 'Factory Information',
        'contact_info': 'Contact Details',
        'country': 'Country',
        'address': 'Address',
        'commercial_reg': 'Commercial Register',
        'tax_number': 'Tax Number',
        'whatsapp': 'WhatsApp',
        'website': 'Website',
        'brand_identity': 'Brand Identity',
        'logo_saved': 'Logo saved ✓',
        'logo_removed': 'Logo removed.',
        'invoice_settings': 'Invoice Settings',
        'thank_you_msg': 'Thank You Message on Invoice',
        'invoice_footer': 'Invoice Footer',
        'appears_in_invoice': 'Appears at bottom of every invoice',
        'system_settings': 'System Settings',
        'default_karat': 'Default Karat',
        'weight_unit': 'Weight Unit',
        'ounce': 'Ounce (oz)',
        'change_email': 'Change Email',
        'change_email_note': 'Changing email requires your current password.',
        'current_email': 'Current Email',
        'new_email': 'New Email',
        'verify_password': 'Password Verification',
        'update_email': 'Update Email',
        'email_updated': 'Email updated ✓',
        'email_taken': 'This email is used by another account.',
        'email_required': 'Email is required.',
        'settings_saved': 'Saved ✓',
        'need_renewal': 'To renew your subscription, contact support',
        'renew_via_whatsapp': 'Renew via WhatsApp',
        'renewal_msg': 'I want to renew my Gold Factory ERP subscription',
        'tech_support': 'Technical Support',
        'backup_restore': 'Backup & Restore',
        'backup_note': 'Backup includes: workers, customers, work orders.',
        'create_backup': 'Download Backup',
        'change_in_security': 'Change email from Security tab',
        'err_wrong_password': 'Current password is incorrect.',
        'last_login_ip': 'Last IP',
        'session_activity': 'Activity & Sessions',
        'logout_all_devices': 'Logout from All Devices',
        'logged_out_all': 'Logged out from all devices.',
        'confirm_logout_all': 'Log out from all devices?',
        'api_key': 'API Key',
        'api_key_note': 'Keep this key safe — never share it.',
        'no_api_key': 'No API Key — generate one',
        'gen_api_key': 'Generate API Key',
        'api_key_generated': 'New API Key generated ✓',
        'confirm_regen_api': 'Regenerating will invalidate the old key. Continue?',
        'report_issue': 'Report an Issue',
        'issue_desc': 'Issue Description',
        'issue_placeholder': 'Describe the issue in detail...',
        'send_report': 'Submit Report',
        'issue_reported': 'Report submitted ✓ — Support will contact you.',
        'factory_qr': 'Factory QR & System Info',
        'download_qr': 'Download QR',
        'server_status': 'Server Status',
        'online': 'Online',
        'factory_color': 'Factory Color',
        'color_note': 'Used in printing and branding',
        'restore_backup': 'Restore Backup',
        'restore_warning': 'Warning: Restoring will replace current data.',
        'select_backup_file': 'Select Backup File',
        'coming_soon': 'Coming soon — will be activated in the next version',
        'account_since': 'Member Since',
        'toggle_mode': 'Toggle Dark/Light Mode',
        'registered_phone': 'Registered Phone Number',
        'change_in_general': 'Change from General tab',
        'not_set': 'Not set',
    },
    'tr': {
        'dashboard': 'Kontrol Paneli',
        'work_orders': 'İş Emirleri',
        'new_order': 'Yeni Emir',
        'workers': 'Çalışanlar',
        'inventory': 'Envanter',
        'reports': 'Raporlar',
        'logout': 'Çıkış',
        'admin_panel': 'Yönetim Paneli',
        'settings': 'Ayarlar',
        'login': 'Giriş',
        'register': 'Kayıt',
        'email': 'E-posta',
        'password': 'Şifre',
        'confirm_password': 'Şifreyi Onayla',
        'factory_name': 'Fabrika Adı',
        'full_name': 'Ad Soyad',
        'city': 'Şehir',
        'phone': 'Telefon',
        'sign_in': 'Giriş Yap',
        'create_account': 'Hesap Oluştur',
        'already_have_account': 'Zaten hesabınız var mı?',
        'no_account': 'Yeni fabrika?',
        'total_gold': 'Toplam Altın',
        'total_loss': 'Toplam Fire',
        'active_orders': 'Aktif Emirler',
        'total_workers': 'Toplam Çalışan',
        'completed_orders': 'Tamamlanan Emirler',
        'monthly_salary': 'Aylık Maaş',
        'recent_orders': 'Son Emirler',
        'inventory_movements': 'Envanter Hareketleri',
        'gold_balance': 'Altın Bakiyesi',
        'grams': 'Gram (g)',
        'sar': 'SAR',
        'order_number': 'Emir No.',
        'model_name': 'Model',
        'customer': 'Müşteri',
        'karat': 'Ayar',
        'initial_weight': 'Başlangıç Ağırlığı',
        'status': 'Durum',
        'date': 'Tarih',
        'actions': 'İşlemler',
        'active': 'Aktif',
        'completed': 'Tamamlandı',
        'cancelled': 'İptal',
        'view': 'Görüntüle',
        'edit': 'Düzenle',
        'delete': 'Sil',
        'add_stage': 'Aşama Ekle',
        'complete_order': 'Emri Tamamla',
        'create_order': 'Emir Oluştur',
        'save': 'Kaydet',
        'cancel': 'İptal',
        'back': 'Geri',
        'notes': 'Notlar',
        'search': 'Ara',
        'filter': 'Filtrele',
        'all': 'Tümü',
        'stage': 'Aşama',
        'worker': 'Çalışan',
        'received_weight': 'Alınan Ağırlık',
        'produced_weight': 'Üretilen Ağırlık',
        'scrap_weight': 'Hurda Altın',
        'loss': 'Fire',
        'gain': 'Kazanç',
        'net_result': 'Net Sonuç',
        'loss_pct': 'Fire %',
        'handover': 'Devir',
        'complete_stage': 'Aşamayı Tamamla',
        'in_progress': 'Devam Ediyor',
        'stage_handover': 'Aşama Devri',
        'stage_completion': 'Aşama Tamamlama',
        'stone_type': 'Taş Türü',
        'stone_color': 'Taş Rengi',
        'stone_weight_ct': 'Taş Ağırlığı (ct)',
        'stone_weight_g': 'Taş Ağırlığı (g)',
        'returned_stone': 'İade Edilen Taşlar',
        'stone_section': 'Taşlar',
        'ct_to_g': '1 karat = 0.2 g',
        'add_movement': 'Hareket Kaydet',
        'movement_type': 'Hareket Türü',
        'incoming': 'Gelen',
        'outgoing': 'Giden',
        'weight': 'Ağırlık',
        'description': 'Kısa Açıklama',
        'trans_date': 'Tarih',
        'salary': 'Maaş',
        'specialty': 'Uzmanlık',
        'add_worker': 'Çalışan Ekle',
        'worker_performance': 'Çalışan Performansı',
        'total_stages': 'Toplam Aşama',
        'completed_stages': 'Tamamlanan Aşamalar',
        'loss_report': 'Fire Raporu',
        'per_stage': 'Aşamaya Göre',
        'per_worker': 'Çalışana Göre',
        'per_order': 'Emre Göre',
        'print': 'Yazdır',
        'total': 'Toplam',
        'factories': 'Fabrikalar',
        'new_factory': 'Yeni Fabrika',
        'activate': 'Etkinleştir',
        'deactivate': 'Devre Dışı',
        'plan': 'Plan',
        'expiry': 'Son Kullanma',
        'subscription': 'Abonelik',
        'confirm_delete': 'Silmeyi Onayla',
        'are_you_sure': 'Emin misiniz?',
        'confirm': 'Onayla',
        'warning': 'Uyarı',
        'loss_warning': "Fire %2'yi aşıyor!",
        'gold_factory': 'Altın Fabrikası',
        'platform_name': 'Altın Fabrikası Platformu',
        'from_stone': 'Taşlardan',
        'stone_unit': 'Taş Birimi',
        'stone_required': 'Gereken Miktar',
        'stone_given': 'İşçiye Verilen',
        'stone_returned': 'İade Edilen Taşlar',
        'stone_used': 'Kullanılan Taş',
        'country_code': 'Ülke Kodu',
        'phone_number': 'Telefon Numarası',
        'otp_code': 'OTP Kodu',
        'verify_phone': 'Telefonu Doğrula',
        'resend_otp': 'Kodu Tekrar Gönder',
        'err_phone_required': 'Telefon numarası gereklidir.',
        'err_code_required': 'Aktivasyon kodu gerekli.',
        'err_code_invalid': 'Geçersiz kod.',
        'err_code_used': 'Kod zaten kullanılmış.',
        'factory_settings': 'Fabrika Bilgileri',
        'account_settings': 'Hesap Ayarları',
        'subscription_settings': 'Abonelik',
        'change_password': 'Şifre Değiştir',
        'factory_logo': 'Fabrika Logosu',
        'activation_code': 'Aktivasyon Kodu',
        'customers': 'Müşteriler',
        'add_customer': 'Müşteri Ekle',
        'customer_type': 'Tür',
        'client': 'Müşteri',
        'supplier': 'Tedarikçi',
        'customer_name': 'Müşteri Adı',
        'product_name': 'Ürün Adı',
        'product_code': 'Ürün Kodu',
        'exports': 'Satışlar ve İhracat',
        'new_export': 'Yeni Satış',
        'new_import': 'Yeni Satın Alma',
        'labor_per_gram': 'Gram Başına İşçilik',
        'labor_total': 'Toplam İşçilik',
        'price_per_gram': 'Fiyat/g',
        'total_price': 'Toplam',
        'export_gold': 'Altın İhraç Et',
        'import_gold': 'Altın İthal Et',
        'production_report': 'Üretim Raporu',
        'inventory_report': 'Envanter Raporu',
        'customers_report': 'Müşteri Raporu',
        'total_produced': 'Toplam Üretim',
        'total_in': 'Toplam Gelen',
        'total_out': 'Toplam Giden',
        'current_balance': 'Mevcut Bakiye',
        'pure_weight': 'Saf Ağırlık (24K)',
        'pure_balance': 'Saf Altın Bakiyesi',
        'pure_in': 'Saf Gelen',
        'pure_out': 'Saf Giden',
        'total_pure_gold': 'Toplam Saf Altın (24K)',
        'karat_label': 'Ayar',
        'pure_formula': 'Saf Ağırlık = Ağırlık × (Ayar ÷ 24)',
        'subscription_expiry': 'Abonelik Sona Erme Tarihi',
        'subscription_status': 'Abonelik Durumu',
        'days_remaining': 'Kalan Gün',
        'gen_code': 'Yeni Kod Oluştur',
        'extend_subscription': 'Aboneliği Uzat',
        'extend_days': 'Gün Sayısı',
        'set_expiry': 'Son Kullanma Tarihi Belirle',
        'sub_active': 'Aktif',
        'sub_expired': 'Süresi Doldu',
        'sub_suspended': 'Askıya Alındı',
        'manage_subscription': 'Aboneliği Yönet',
        'reset_password': 'Şifreyi Sıfırla',
        'new_password': 'Yeni Şifre',
        'err_invalid_credentials': 'Geçersiz e-posta veya şifre.',
        'err_account_deactivated': 'Hesap devre dışı.',
        'err_suspended': 'Fabrika askıya alındı.',
        'err_expired': 'Abonelik süresi doldu.',
        'err_weight_positive': 'Ağırlık sıfırdan büyük olmalıdır.',
        'msg_movement_saved': 'Kaydedildi.',
        'msg_deleted': 'Silindi.',
        'msg_settings_saved': 'Ayarlar kaydedildi.',
        'activated': 'Etkinleştirildi',
        'deactivated': 'Devre Dışı Bırakıldı',
        'expired_factories': 'Süresi Dolan Abonelikler',
        'sub_expiry_date': 'Son Kullanma Tarihi',
        'never': 'Sınırsız',
        'day': 'gün',
        'days': 'gün',
        'employees': 'Çalışanlar',
        'employee_code': 'Çalışan Kodu',
        'employee_name': 'Çalışan Adı',
        'employee_role': 'Meslek / Uzmanlık',
        'employee_salary': 'Aylık Maaş',
        'employee_phone': 'Telefon',
        'employee_add': 'Çalışan Ekle',
        'employee_list': 'Çalışan Listesi',
        'employee_analysis': 'Çalışan Analizi',
        'employee_terminated': 'Eski Çalışanlar',
        'employee_terminate': 'İşten Çıkar',
        'employee_id_card': 'Kimlik Kartı',
        'employee_status_active': 'Aktif',
        'employee_status_off': 'İşten Çıkarıldı',
        'employee_dob': 'Doğum Tarihi',
        'employee_age': 'Yaş',
        'employee_id_number': 'Kimlik No.',
        'employee_id_expiry': 'Son Geçerlilik',
        'employee_nationality': 'Uyruk',
        'termination_date': 'İşten Çıkış Tarihi',
        'termination_notes': 'Çıkış Notları',
        'salary_due': 'Kıdem Tazminatı',
        'worked_days': 'Çalışılan Gün',
        'efficiency': 'Verimlilik',
        'loss_pct_label': 'Fire %',
        'total_received': 'Toplam Alınan',
        'total_produced_label': 'Toplam Üretilen',
        'total_loss_label': 'Toplam Fire',
        'karat_analysis': 'Ayara Göre Analiz',
        'production_stages': 'Üretim Aşamaları',
        'net_24k': 'Net 24K',
        'customer_code': 'Müşteri Kodu',
        'customer_list': 'Müşteri Listesi',
        'customer_analysis': 'Müşteri Analizi',
        'customer_profile': 'Müşteri Profili',
        'statement': 'Hesap Özeti',
        'returns': 'İadeler',
        'return_add': 'İade Ekle',
        'allowed_return': 'İade Edilebilir',
        'balance': 'Bakiye',
        'debtor': 'Borçlu',
        'creditor': 'Alacaklı',
        'balanced': 'Dengeli',
        'total_sent': 'Toplam Gönderilen',
        'total_recv': 'Toplam Alınan',
        'total_ret': 'Toplam İade',
        'last_transaction': 'Son İşlem',
        'products': 'Ürünler',
        'product_inventory': 'Ürün Envanteri',
        'product_add': 'Ürün Ekle',
        'product_analysis': 'Ürün Analizi',
        'unit_weight': 'Birim Ağırlık',
        'total_weight': 'Toplam Ağırlık',
        'quantity': 'Miktar',
        'input_mode_unit': 'Birim',
        'input_mode_bulk': 'Toplu',
        'input_mode_single': 'Tekil',
        'sales': 'Satışlar',
        'purchases': 'Satın Almalar',
        'new_sale': 'Yeni Satış',
        'new_purchase': 'Yeni Satın Alma',
        'sale_list': 'Satış Listesi',
        'purchase_list': 'Satın Alma Listesi',
        'sale_type_product': 'Hazır Ürün',
        'sale_type_gold': 'Ham Altın',
        'operation_code': 'İşlem Kodu',
        'total_value': 'Toplam Değer',
        'ref_sale': 'Referans Satış',
        'reports_products': 'Ürün Raporu',
        'reports_purchases': 'Satın Alma Raporu',
        'reports_sales': 'Satış Raporu',
        'reports_archive': 'Arşiv',
        'archive_new': 'Yeni Arşiv',
        'archive_label': 'Arşiv Başlığı',
        'archive_from': 'Başlangıç Tarihi',
        'archive_to': 'Bitiş Tarihi',
        'archive_confirm_pw': 'Onay Şifresi',
        'archive_save': 'Arşivi Kaydet',
        'archive_view': 'Görüntüle',
        'date_from': 'Başlangıç',
        'date_to': 'Bitiş',
        'upload_logo': 'Logo Yükle',
        'remove_logo': 'Logoyu Kaldır',
        'logo_size_limit': 'Maks 500KB',
        'language': 'Dil',
        'language_tr': 'Türkçe',
        'dir': 'ltr',
        'active_label': 'Aktif',
        'inactive_label': 'Pasif',
        'terminated_label': 'İşten Çıkarıldı',
        'expired_label': 'Süresi Doldu',
        'id_expired_badge': 'Kimlik Süresi Doldu',
        'private_label': 'Özel',
        'balanced_label': 'Dengeli',
        'add_to_inventory': 'Envantere Ekle',
        'print_card': 'Kimlik Kartı Yazdır',
        'terminate_service': 'İşten Çıkar',
        'close_modal': 'Kapat',
        'archive_btn': 'Arşivle',
        'save_archive_btn': 'Arşivi Kaydet',
        'new_sale_btn': 'Yeni Satış',
        'new_purchase_btn': 'Yeni Satın Alma',
        'register_sale': 'Satışı Kaydet',
        'register_purchase': 'Satın Almayı Kaydet',
        'invoice_btn': 'Fatura',
        'invoice_sale': 'Satış Faturası',
        'invoice_purchase': 'Satın Alma Faturası',
        'upload_logo_btn': 'Logo Yükle',
        'remove_logo_btn': 'Logoyu Kaldır',
        'open_order': 'Emri Aç',
        'back_to_order': 'Emre Geri Dön',
        'end_edit': 'Düzenlemeyi Bitir',
        'employee_active_list': 'Aktif Çalışanlar',
        'customers_list_label': 'Müşteri Listesi',
        'employee_list_label': 'Çalışan Listesi',
        'customers_statement': 'Müşteri Özeti',
        'sales_statement': 'Satış Özeti',
        'purchases_statement': 'Satın Alma Özeti',
        'settlement_summary': 'Uzlaşma Özeti',
        'personal_info': 'Kişisel Bilgiler',
        'inventory_board': 'Envanter Paneli',
        'gold_movements': 'Altın Hareketleri',
        'product_stock': 'Ürün Stoğu',
        'product_analysis_nav': 'Ürün Analizi',
        'customer_analysis_nav': 'Müşteri Analizi',
        'employee_analysis_nav': 'Çalışan Analizi',
        'add_employee_nav': 'Çalışan Ekle',
        'add_customer_nav': 'Müşteri Ekle',
        'add_product_nav': 'Ürün Ekle',
        'top_production': 'En Yüksek Üretim',
        'lowest_loss': 'En Düşük Fire',
        'most_operations': 'En Fazla İşlem',
        'top_by_sales': 'Satışa Göre İlk 5',
        'highest_debtors': 'İlk 5 Borçlu',
        'password_confirm_label': 'Şifre *',
        'confirm_terminate': 'Çıkışı Onayla',
        'from_work_order': 'İş Emrinden',
        'to_work_order': 'İş Emrine',
        'from_products': 'Ürünlerden',
        'from_customer': 'Müşteriden',
        'to_customer': 'Müşteriye',
        'print_btn': 'Yazdır',
        'archive_period': 'Dönemi Arşivle',
        'new_archive_btn': 'Yeni Arşiv',
        'currently_active': 'Aktif',
        'in_progress_badge': 'Devam Ediyor',
        'completed_badge': 'Tamamlandı',
        'cancelled_badge': 'İptal',
        'debtor_badge': 'Borçlu',
        'creditor_badge': 'Alacaklı',
        'op_code': 'İşlem Kodu',
        'sale_type': 'İşlem Türü',
        'transaction_date': 'İşlem Tarihi',
        'total_products': 'Ürünler',
        'total_ops': 'İşlemler',
        'today_ops': 'Bugünkü İşlemler',
        'registered_workers': 'Kayıtlı Çalışanlar',
        'total_customers': 'Toplam Müşteri',
        'all_orders': 'Toplam Emir',
        'best_worker_label': 'En İyi Çalışan (En Az Fire)',
        'worst_stage_label': 'En Yüksek Fire Aşaması',
        'top_client_label': 'En Çok İşlem Yapan Müşteri',
        'sales_and_purchases': 'Satış + Satın Alma',
        'today': 'Bugün',
        'in_inventory': 'Stokta',
        'no_data': 'Henüz veri yok',
        'total_production_label': 'Toplam Üretim (24K)',
        'total_scrap_label': 'Toplam Altın Hurda (24K)',
        'employees_count': 'Çalışan Sayısı',
        'customers_count': 'Müşteri Sayısı',
        'add_factory': '+ Fabrika Ekle',
        'alerts': 'Uyarılar',
        'completion_pct': 'Tamamlanma Oranı',
        'expiring_soon': '7 günde Sona Erecek',
        'inactive_factories': 'Pasif Fabrikalar',
        'more': 'daha fazla',
        'factory_code_label': 'Fabrika Kodu',
        'factory_code_new': 'Yeni Kod',
        'copy': 'Kopyala',
        'system_team': 'Sistem Ekibi',
        'system_team_desc': 'Platform yönetim ekibi — fabrikalardan bağımsız',
        'add_team_member': '+ Personel Ekle',
        'team_member_info': 'Personel Bilgileri',
        'team_note': 'Personel kodu otomatik oluşturulacak (EMP-XXXX)',
        'system_role_label': 'Rol',
        'role_support': 'Destek',
        'role_accountant': 'Muhasebe',
        'role_manager': 'Yönetici',
        'no_team_members': 'Henüz personel yok',
        'factory_users': 'Fabrika Kullanıcıları',
        'factory_users_desc': 'Platformdaki fabrika sahipleri',
        'last_login': 'Son Giriş',
        'total_factories_label': 'Toplam Fabrika',
        'active_factories_label': 'Aktif Fabrikalar',
        'total_orders_label': 'Toplam Emir',
        'platform_activity': 'Platform Aktivitesi',
        'subscriptions': 'Abonelik Yönetimi',
        'unlimited_subs': 'Sınırsız Abonelik',
        'expiring_30': '30 günde Sona Erecek',
        'across_all_factories': 'Tüm Fabrikalarda',
        'quick_links': 'Hızlı Bağlantılar',
        'staff_limited_access': 'Bazı işlemler rolünüze göre kısıtlıdır',
        'is_active': 'Durum',
        'slot_desc': 'Fabrikaya paylaşmak için aktivasyon kodu oluşturun — /auth/register adresinde kullanılır',
        'generate_code': 'Yeni Kod Oluştur',
        'total_codes': 'Toplam Kod',
        'unused_codes': 'Kullanılmayan',
        'used_codes': 'Kullanılan',
        'disabled_codes': 'Devre Dışı',
        'optional': 'İsteğe Bağlı',
        'print_preview': 'Baskı Önizleme',
        'generate_to_preview': 'Önizleme için kod oluşturun',
        'all_codes': 'Tüm Kodlar',
        'no_codes_yet': 'Henüz kod yok — bir tane oluşturun',
        'register_at': 'Kayıt adresi',
        'pending': 'Beklemede',
        'contact_support': 'Destek ile İletişim',
        'whatsapp_msg': 'Merhaba, Altın Fabrikası sistemi hakkında bir sorum var',
        'platform_settings': 'Platform Ayarları',
        'platform_settings_desc': 'Platform kimliği ve iletişim bilgileri',
        'whatsapp_settings': 'WhatsApp Ayarları',
        'support_whatsapp_label': 'Müşteri Destek Numarası (WhatsApp)',
        'whatsapp_note': 'Uluslararası format girin, örn: +905396672357',
        'test_link': 'Bağlantıyı Test Et',
        'preview': 'Bağlantı Önizleme',
        'print_footer_note': 'Gold Factory Sistemi tarafından oluşturuldu',
        'thank_you': 'İlginiz için teşekkür ederiz',
        'invoice_date': 'Fatura Tarihi',
        'platform_identity': 'Platform Kimliği',
        'platform_name_label': 'Platform Adı',
        'platform_tagline_label': 'Slogan',
        'platform_version_label': 'Sürüm',
        'contact_settings': 'İletişim Bilgileri',
        'support_email_label': 'Destek E-postası',
        'forgot_password': 'Şifremi Unuttum',
        'forgot_password_desc': 'Kimliğinizi doğrulamak için e-posta ve telefon numaranızı girin',
        'verify_identity': 'Kimliği Doğrula',
        'verify_both_required': 'E-posta ve telefon hesabınızla eşleşmelidir',
        'back_to_login': 'Girişe Dön',
        'need_help': 'Yardım lazım mı?',
        'save_password': 'Şifreyi Kaydet',
        'session_expires_note': 'Bu oturum 15 dakika içinde sona erer',
        'password_updated': 'Şifre başarıyla güncellendi. Giriş yapabilirsiniz.',
        'err_reset_mismatch': 'Bilgiler eşleşmiyor — e-posta ve telefon numaranızı kontrol edin.',
        'err_rate_limit': 'Çok fazla deneme — 15 dakika bekleyin.',
        'err_session_expired': 'Oturum süresi doldu — lütfen yeni bir sıfırlama isteyin.',
        'err_password_short': 'Şifre en az 8 karakter olmalıdır.',
        'err_password_mismatch': 'Şifreler eşleşmiyor.',
        'passwords_match': '✓ Şifreler eşleşiyor',
        'pw_weak': 'Zayıf',
        'pw_fair': 'Orta',
        'pw_good': 'İyi',
        'pw_strong': 'Güçlü ✓',
        'total_revenue': 'Toplam Gelir',
        'month_revenue': 'Bu Ay Geliri',
        'active_subs': 'Aktif Abonelikler',
        'expired_subs': 'Süresi Dolmuş',
        'total_payments': 'Toplam Ödeme',
        'payment_history': 'Ödeme Geçmişi',
        'add_payment': 'Ödeme Kaydet',
        'payment_recorded': 'Ödeme Kaydedildi',
        'payment_method': 'Ödeme Yöntemi',
        'payment_status': 'Ödeme Durumu',
        'payment_note': 'Kayıt sonrası abonelik otomatik uzatılacak.',
        'record_payment': 'Ödemeyi Kaydet',
        'bank_transfer': 'Banka Transferi',
        'cash': 'Nakit',
        'manual': 'Manuel',
        'paid': 'Ödendi',
        'refunded': 'İade Edildi',
        'failed': 'Başarısız',
        'invoice_no': 'Fatura No',
        'all_payments': 'Tüm Ödemeler',
        'no_payments_yet': 'Henüz ödeme yok',
        'recorded_by': 'Kaydeden',
        'amount': 'Tutar',
        'period': 'Süre',
        'currency': 'Para Birimi',
        'plans': 'Planlar',
        'plan_name': 'Plan Adı',
        'price_month': 'Aylık Fiyat',
        'price_year': 'Yıllık Fiyat',
        'month': 'Ay',
        'year': 'Yıl',
        'health_score': 'Hesap Sağlığı',
        'factory_notes': 'Dahili Notlar',
        'add_note': 'Not ekle...',
        'no_notes': 'Henüz not yok',
        'note_general': 'Genel',
        'note_payment': 'Ödeme',
        'note_contacted': 'İletişim Kuruldu',
        'note_discount': 'İndirim',
        'note_issue': 'Sorun',
        'select': 'Seç',
        'analytics': 'Analizler',
        'monthly_revenue': 'Aylık Gelir',
        'avg_sub_value': 'Ortalama Abonelik Değeri',
        'top_payers': 'En Çok Ödeyen Fabrikalar',
        'recalc_health': 'Sağlık Puanlarını Güncelle',
        'err_read_only': 'Hesabınız Salt Okunur modda — abonelik sona erdi. Yönetici ile iletişime geçin.',
        'err_grace_period': '⚠️ Abonelik sona erdi — tolerans süresi aktif. Lütfen yakında yenileyin.',
        'tab_general': 'Genel',
        'tab_identity': 'Kimlik',
        'tab_invoice': 'Faturalar',
        'tab_system': 'Sistem',
        'tab_security': 'Güvenlik',
        'tab_subscription': 'Abonelik',
        'tab_support': 'Destek',
        'factory_info': 'Fabrika Bilgileri',
        'contact_info': 'İletişim Bilgileri',
        'country': 'Ülke',
        'address': 'Adres',
        'commercial_reg': 'Ticaret Sicili',
        'tax_number': 'Vergi Numarası',
        'whatsapp': 'WhatsApp',
        'website': 'Web Sitesi',
        'brand_identity': 'Marka Kimliği',
        'logo_saved': 'Logo kaydedildi ✓',
        'logo_removed': 'Logo kaldırıldı.',
        'invoice_settings': 'Fatura Ayarları',
        'thank_you_msg': 'Faturadaki Teşekkür Mesajı',
        'invoice_footer': 'Fatura Alt Bilgisi',
        'appears_in_invoice': 'Her faturanın altında görünür',
        'system_settings': 'Sistem Ayarları',
        'default_karat': 'Varsayılan Ayar',
        'weight_unit': 'Ağırlık Birimi',
        'ounce': 'Ons (oz)',
        'change_email': 'E-posta Değiştir',
        'change_email_note': 'E-posta değiştirmek için mevcut şifrenizi doğrulamanız gerekir.',
        'current_email': 'Mevcut E-posta',
        'new_email': 'Yeni E-posta',
        'verify_password': 'Şifre Doğrulama',
        'update_email': 'E-postayı Güncelle',
        'email_updated': 'E-posta güncellendi ✓',
        'email_taken': 'Bu e-posta başka bir hesap tarafından kullanılıyor.',
        'email_required': 'E-posta gereklidir.',
        'settings_saved': 'Kaydedildi ✓',
        'need_renewal': 'Aboneliğinizi yenilemek için destek ile iletişime geçin',
        'renew_via_whatsapp': 'WhatsApp ile Yenile',
        'renewal_msg': 'Gold Factory ERP aboneliğimi yenilemek istiyorum',
        'tech_support': 'Teknik Destek',
        'backup_restore': 'Yedekleme ve Geri Yükleme',
        'backup_note': 'Yedek şunları içerir: çalışanlar, müşteriler, iş emirleri.',
        'create_backup': 'Yedek İndir',
        'change_in_security': 'E-postayı Güvenlik sekmesinden değiştirin',
        'err_wrong_password': 'Mevcut şifre yanlış.',
        'last_login_ip': 'Son IP',
        'session_activity': 'Aktivite ve Oturumlar',
        'logout_all_devices': 'Tüm Cihazlardan Çıkış',
        'logged_out_all': 'Tüm cihazlardan çıkış yapıldı.',
        'confirm_logout_all': 'Tüm cihazlardan çıkış yapmak istiyor musunuz?',
        'api_key': 'API Anahtarı',
        'api_key_note': 'Bu anahtarı güvende tutun — kimseyle paylaşmayın.',
        'no_api_key': 'API Anahtarı yok — oluşturun',
        'gen_api_key': 'API Anahtarı Oluştur',
        'api_key_generated': 'Yeni API Anahtarı oluşturuldu ✓',
        'confirm_regen_api': 'Yeniden oluşturma eski anahtarı geçersiz kılacak. Devam?',
        'report_issue': 'Sorun Bildir',
        'issue_desc': 'Sorun Açıklaması',
        'issue_placeholder': 'Sorunu ayrıntılı açıklayın...',
        'send_report': 'Raporu Gönder',
        'issue_reported': 'Rapor gönderildi ✓ — Destek ekibi sizinle iletişime geçecek.',
        'factory_qr': 'Fabrika QR ve Sistem Bilgileri',
        'download_qr': 'QR İndir',
        'server_status': 'Sunucu Durumu',
        'online': 'Çevrimiçi',
        'factory_color': 'Fabrika Rengi',
        'color_note': 'Baskı ve markalaşmada kullanılır',
        'restore_backup': 'Yedeği Geri Yükle',
        'restore_warning': 'Uyarı: Geri yükleme mevcut verilerin üzerine yazar.',
        'select_backup_file': 'Yedek Dosyası Seç',
        'coming_soon': 'Yakında — bir sonraki sürümde etkinleştirilecek',
        'account_since': 'Üyelik Tarihi',
        'toggle_mode': 'Karanlık/Aydınlık Modu Değiştir',
        'registered_phone': 'Kayıtlı Telefon Numarası',
        'change_in_general': 'Genel sekmesinden değiştirin',
        'not_set': 'Belirlenmedi',
    },
}
































def create_app(env='default'):
    app = Flask(__name__)
    app.config.from_object(config[env])

    init_extensions(app)

    # ── Language helper ───────────────────────────────────────
    @app.before_request
    def set_language():
        g.lang = session.get('lang', 'ar')
        if g.lang not in TRANSLATIONS:
            g.lang = 'ar'
        # ChainMap: requested lang → AR fallback (no KeyError for new keys)
        from collections import ChainMap
        g.t   = ChainMap(TRANSLATIONS[g.lang], TRANSLATIONS['ar'])
        g.dir = TRANSLATIONS[g.lang].get('dir', 'rtl')

    @app.context_processor
    def inject_globals():
        from flask_login import current_user

        # Auto-translate helper: tr('نشط') → 'Active' in EN, 'Aktif' in TR
        # Build reverse lookup: AR value → key (done once per request)
        ar_to_key = {v: k for k, v in TRANSLATIONS['ar'].items()}

        def tr(arabic_text):
            """Translate Arabic text to current language automatically."""
            if g.lang == 'ar':
                return arabic_text
            key = ar_to_key.get(arabic_text)
            if key:
                return g.t.get(key, arabic_text)
            return arabic_text   # fallback: return as-is

        return dict(
            t=g.t, lang=g.lang, dir=g.dir,
            **_get_platform_settings(),
            now=datetime.utcnow(),
            current_user=current_user,
            tr=tr,
        )

    # ── Blueprints ────────────────────────────────────────────
    from routes.auth    import auth_bp
    from routes.admin   import admin_bp
    from routes.factory import factory_bp
    from routes.orders  import orders_bp
    from routes.workers import workers_bp
    from routes.reports import reports_bp
    from routes.customers import customers_bp
    from routes.exports   import exports_bp

    app.register_blueprint(auth_bp,      url_prefix='/auth')
    app.register_blueprint(admin_bp,     url_prefix='/admin')
    app.register_blueprint(factory_bp,   url_prefix='/factory')
    app.register_blueprint(orders_bp,    url_prefix='/orders')
    app.register_blueprint(workers_bp,   url_prefix='/workers')
    app.register_blueprint(reports_bp,   url_prefix='/reports')
    app.register_blueprint(customers_bp, url_prefix='/customers')
    from routes.product_inventory import prod_inv_bp
    app.register_blueprint(exports_bp,   url_prefix='/exports')
    app.register_blueprint(prod_inv_bp,  url_prefix='/products')

    # ── Language switch ───────────────────────────────────────
    @app.route('/lang/<code>')
    def lang(code):
        if code in ('ar', 'en', 'tr'):
            session['lang'] = code
        return redirect(freq.referrer or '/')

    # ── Root ──────────────────────────────────────────────────
    @app.route('/')
    def index():
        from flask_login import current_user
        if current_user.is_authenticated:
            if current_user.is_superadmin:
                return redirect(url_for('admin.dashboard'))
            return redirect(url_for('factory.dashboard'))
        ps = _get_platform_settings()
        return render_template('landing.html',
                               platform_name=ps['platform_name'],
                               platform_version=ps['platform_version'],
                               support_whatsapp=ps['support_whatsapp'],
                               support_email=ps['support_email'])

    # ── Error handlers ────────────────────────────────────────
    @app.errorhandler(403)
    def forbidden(e):
        return render_template('errors/403.html'), 403

    @app.errorhandler(404)
    def not_found(e):
        return render_template('errors/404.html'), 404

    return app


if __name__ == '__main__':
    app = create_app('development')
    print("=" * 55)
    print("  ⚜  Gold Factory SaaS Platform v5.0")
    print("  🌐  http://127.0.0.1:5000")
    print()
    print("  👑  Super Admin:")
    print("      admin@goldplatform.com / Admin@12345")
    print()
    print("  🏭  Factory: /register  or  /auth/login")
    print("=" * 55)
    app.run(debug=True, host='0.0.0.0', port=5000)
