# World countries list — (iso2_code, {ar, en, tr})
_COUNTRIES = [
    ('AF', {'ar': 'أفغانستان',           'en': 'Afghanistan',              'tr': 'Afganistan'}),
    ('AL', {'ar': 'ألبانيا',              'en': 'Albania',                  'tr': 'Arnavutluk'}),
    ('DZ', {'ar': 'الجزائر',             'en': 'Algeria',                  'tr': 'Cezayir'}),
    ('AD', {'ar': 'أندورا',              'en': 'Andorra',                  'tr': 'Andorra'}),
    ('AO', {'ar': 'أنغولا',              'en': 'Angola',                   'tr': 'Angola'}),
    ('AR', {'ar': 'الأرجنتين',           'en': 'Argentina',                'tr': 'Arjantin'}),
    ('AM', {'ar': 'أرمينيا',             'en': 'Armenia',                  'tr': 'Ermenistan'}),
    ('AU', {'ar': 'أستراليا',            'en': 'Australia',                'tr': 'Avustralya'}),
    ('AT', {'ar': 'النمسا',              'en': 'Austria',                  'tr': 'Avusturya'}),
    ('AZ', {'ar': 'أذربيجان',            'en': 'Azerbaijan',               'tr': 'Azerbaycan'}),
    ('BH', {'ar': 'البحرين',             'en': 'Bahrain',                  'tr': 'Bahreyn'}),
    ('BD', {'ar': 'بنغلاديش',            'en': 'Bangladesh',               'tr': 'Bangladeş'}),
    ('BY', {'ar': 'بيلاروسيا',           'en': 'Belarus',                  'tr': 'Beyaz Rusya'}),
    ('BE', {'ar': 'بلجيكا',              'en': 'Belgium',                  'tr': 'Belçika'}),
    ('BZ', {'ar': 'بليز',               'en': 'Belize',                   'tr': 'Belize'}),
    ('BJ', {'ar': 'بنين',               'en': 'Benin',                    'tr': 'Benin'}),
    ('BT', {'ar': 'بوتان',              'en': 'Bhutan',                   'tr': 'Bhutan'}),
    ('BO', {'ar': 'بوليفيا',             'en': 'Bolivia',                  'tr': 'Bolivya'}),
    ('BA', {'ar': 'البوسنة والهرسك',     'en': 'Bosnia and Herzegovina',   'tr': 'Bosna Hersek'}),
    ('BW', {'ar': 'بتسوانا',             'en': 'Botswana',                 'tr': 'Botsvana'}),
    ('BR', {'ar': 'البرازيل',            'en': 'Brazil',                   'tr': 'Brezilya'}),
    ('BN', {'ar': 'بروناي',             'en': 'Brunei',                   'tr': 'Brunei'}),
    ('BG', {'ar': 'بلغاريا',             'en': 'Bulgaria',                 'tr': 'Bulgaristan'}),
    ('BF', {'ar': 'بوركينا فاسو',        'en': 'Burkina Faso',             'tr': 'Burkina Faso'}),
    ('BI', {'ar': 'بوروندي',             'en': 'Burundi',                  'tr': 'Burundi'}),
    ('KH', {'ar': 'كمبوديا',             'en': 'Cambodia',                 'tr': 'Kamboçya'}),
    ('CM', {'ar': 'الكاميرون',           'en': 'Cameroon',                 'tr': 'Kamerun'}),
    ('CA', {'ar': 'كندا',               'en': 'Canada',                   'tr': 'Kanada'}),
    ('CV', {'ar': 'الرأس الأخضر',        'en': 'Cape Verde',               'tr': 'Yeşil Burun Adaları'}),
    ('CF', {'ar': 'أفريقيا الوسطى',     'en': 'Central African Republic', 'tr': 'Orta Afrika Cumhuriyeti'}),
    ('TD', {'ar': 'تشاد',               'en': 'Chad',                     'tr': 'Çad'}),
    ('CL', {'ar': 'تشيلي',              'en': 'Chile',                    'tr': 'Şili'}),
    ('CN', {'ar': 'الصين',              'en': 'China',                    'tr': 'Çin'}),
    ('CO', {'ar': 'كولومبيا',            'en': 'Colombia',                 'tr': 'Kolombiya'}),
    ('KM', {'ar': 'جزر القمر',          'en': 'Comoros',                  'tr': 'Komorlar'}),
    ('CG', {'ar': 'الكونغو',            'en': 'Congo',                    'tr': 'Kongo'}),
    ('CR', {'ar': 'كوستاريكا',           'en': 'Costa Rica',               'tr': 'Kosta Rika'}),
    ('HR', {'ar': 'كرواتيا',             'en': 'Croatia',                  'tr': 'Hırvatistan'}),
    ('CU', {'ar': 'كوبا',               'en': 'Cuba',                     'tr': 'Küba'}),
    ('CY', {'ar': 'قبرص',               'en': 'Cyprus',                   'tr': 'Kıbrıs'}),
    ('CZ', {'ar': 'التشيك',             'en': 'Czech Republic',            'tr': 'Çek Cumhuriyeti'}),
    ('DK', {'ar': 'الدنمارك',            'en': 'Denmark',                  'tr': 'Danimarka'}),
    ('DJ', {'ar': 'جيبوتي',             'en': 'Djibouti',                 'tr': 'Cibuti'}),
    ('DO', {'ar': 'الدومينيكان',         'en': 'Dominican Republic',       'tr': 'Dominik Cumhuriyeti'}),
    ('EC', {'ar': 'الإكوادور',           'en': 'Ecuador',                  'tr': 'Ekvador'}),
    ('EG', {'ar': 'مصر',                'en': 'Egypt',                    'tr': 'Mısır'}),
    ('SV', {'ar': 'السلفادور',           'en': 'El Salvador',              'tr': 'El Salvador'}),
    ('GQ', {'ar': 'غينيا الاستوائية',   'en': 'Equatorial Guinea',        'tr': 'Ekvator Ginesi'}),
    ('ER', {'ar': 'إريتريا',             'en': 'Eritrea',                  'tr': 'Eritre'}),
    ('EE', {'ar': 'إستونيا',             'en': 'Estonia',                  'tr': 'Estonya'}),
    ('ET', {'ar': 'إثيوبيا',             'en': 'Ethiopia',                 'tr': 'Etiyopya'}),
    ('FJ', {'ar': 'فيجي',               'en': 'Fiji',                     'tr': 'Fiji'}),
    ('FI', {'ar': 'فنلندا',              'en': 'Finland',                  'tr': 'Finlandiya'}),
    ('FR', {'ar': 'فرنسا',              'en': 'France',                   'tr': 'Fransa'}),
    ('GA', {'ar': 'الغابون',             'en': 'Gabon',                    'tr': 'Gabon'}),
    ('GM', {'ar': 'غامبيا',             'en': 'Gambia',                   'tr': 'Gambiya'}),
    ('GE', {'ar': 'جورجيا',             'en': 'Georgia',                  'tr': 'Gürcistan'}),
    ('DE', {'ar': 'ألمانيا',             'en': 'Germany',                  'tr': 'Almanya'}),
    ('GH', {'ar': 'غانا',               'en': 'Ghana',                    'tr': 'Gana'}),
    ('GR', {'ar': 'اليونان',             'en': 'Greece',                   'tr': 'Yunanistan'}),
    ('GT', {'ar': 'غواتيمالا',           'en': 'Guatemala',                'tr': 'Guatemala'}),
    ('GN', {'ar': 'غينيا',              'en': 'Guinea',                   'tr': 'Gine'}),
    ('GW', {'ar': 'غينيا بيساو',        'en': 'Guinea-Bissau',            'tr': 'Gine-Bissau'}),
    ('GY', {'ar': 'غيانا',              'en': 'Guyana',                   'tr': 'Guyana'}),
    ('HT', {'ar': 'هايتي',              'en': 'Haiti',                    'tr': 'Haiti'}),
    ('HN', {'ar': 'هندوراس',            'en': 'Honduras',                 'tr': 'Honduras'}),
    ('HU', {'ar': 'المجر',              'en': 'Hungary',                  'tr': 'Macaristan'}),
    ('IS', {'ar': 'آيسلندا',             'en': 'Iceland',                  'tr': 'İzlanda'}),
    ('IN', {'ar': 'الهند',              'en': 'India',                    'tr': 'Hindistan'}),
    ('ID', {'ar': 'إندونيسيا',           'en': 'Indonesia',                'tr': 'Endonezya'}),
    ('IR', {'ar': 'إيران',              'en': 'Iran',                     'tr': 'İran'}),
    ('IQ', {'ar': 'العراق',             'en': 'Iraq',                     'tr': 'Irak'}),
    ('IE', {'ar': 'أيرلندا',             'en': 'Ireland',                  'tr': 'İrlanda'}),
    ('IL', {'ar': 'إسرائيل',             'en': 'Israel',                   'tr': 'İsrail'}),
    ('IT', {'ar': 'إيطاليا',             'en': 'Italy',                    'tr': 'İtalya'}),
    ('JM', {'ar': 'جامايكا',             'en': 'Jamaica',                  'tr': 'Jamaika'}),
    ('JP', {'ar': 'اليابان',             'en': 'Japan',                    'tr': 'Japonya'}),
    ('JO', {'ar': 'الأردن',             'en': 'Jordan',                   'tr': 'Ürdün'}),
    ('KZ', {'ar': 'كازاخستان',           'en': 'Kazakhstan',               'tr': 'Kazakistan'}),
    ('KE', {'ar': 'كينيا',              'en': 'Kenya',                    'tr': 'Kenya'}),
    ('KI', {'ar': 'كيريباتي',            'en': 'Kiribati',                 'tr': 'Kiribati'}),
    ('KP', {'ar': 'كوريا الشمالية',     'en': 'North Korea',              'tr': 'Kuzey Kore'}),
    ('KR', {'ar': 'كوريا الجنوبية',     'en': 'South Korea',              'tr': 'Güney Kore'}),
    ('KW', {'ar': 'الكويت',             'en': 'Kuwait',                   'tr': 'Kuveyt'}),
    ('KG', {'ar': 'قيرغيزستان',          'en': 'Kyrgyzstan',               'tr': 'Kırgızistan'}),
    ('LA', {'ar': 'لاوس',               'en': 'Laos',                     'tr': 'Laos'}),
    ('LV', {'ar': 'لاتفيا',             'en': 'Latvia',                   'tr': 'Letonya'}),
    ('LB', {'ar': 'لبنان',              'en': 'Lebanon',                  'tr': 'Lübnan'}),
    ('LS', {'ar': 'ليسوتو',             'en': 'Lesotho',                  'tr': 'Lesotho'}),
    ('LR', {'ar': 'ليبيريا',            'en': 'Liberia',                  'tr': 'Liberya'}),
    ('LY', {'ar': 'ليبيا',              'en': 'Libya',                    'tr': 'Libya'}),
    ('LI', {'ar': 'ليختنشتاين',          'en': 'Liechtenstein',            'tr': 'Lihtenştayn'}),
    ('LT', {'ar': 'ليتوانيا',            'en': 'Lithuania',                'tr': 'Litvanya'}),
    ('LU', {'ar': 'لوكسمبورغ',          'en': 'Luxembourg',               'tr': 'Lüksemburg'}),
    ('MG', {'ar': 'مدغشقر',             'en': 'Madagascar',               'tr': 'Madagaskar'}),
    ('MW', {'ar': 'مالاوي',             'en': 'Malawi',                   'tr': 'Malavi'}),
    ('MY', {'ar': 'ماليزيا',             'en': 'Malaysia',                 'tr': 'Malezya'}),
    ('MV', {'ar': 'المالديف',            'en': 'Maldives',                 'tr': 'Maldivler'}),
    ('ML', {'ar': 'مالي',               'en': 'Mali',                     'tr': 'Mali'}),
    ('MT', {'ar': 'مالطا',              'en': 'Malta',                    'tr': 'Malta'}),
    ('MR', {'ar': 'موريتانيا',           'en': 'Mauritania',               'tr': 'Moritanya'}),
    ('MU', {'ar': 'موريشيوس',           'en': 'Mauritius',                'tr': 'Mauritius'}),
    ('MX', {'ar': 'المكسيك',            'en': 'Mexico',                   'tr': 'Meksika'}),
    ('FM', {'ar': 'ميكرونيزيا',          'en': 'Micronesia',               'tr': 'Mikronezya'}),
    ('MD', {'ar': 'مولدوفا',            'en': 'Moldova',                  'tr': 'Moldova'}),
    ('MC', {'ar': 'موناكو',             'en': 'Monaco',                   'tr': 'Monako'}),
    ('MN', {'ar': 'منغوليا',            'en': 'Mongolia',                 'tr': 'Moğolistan'}),
    ('ME', {'ar': 'الجبل الأسود',        'en': 'Montenegro',               'tr': 'Karadağ'}),
    ('MA', {'ar': 'المغرب',             'en': 'Morocco',                  'tr': 'Fas'}),
    ('MZ', {'ar': 'موزمبيق',            'en': 'Mozambique',               'tr': 'Mozambik'}),
    ('MM', {'ar': 'ميانمار',            'en': 'Myanmar',                  'tr': 'Myanmar'}),
    ('NA', {'ar': 'ناميبيا',             'en': 'Namibia',                  'tr': 'Namibya'}),
    ('NP', {'ar': 'نيبال',              'en': 'Nepal',                    'tr': 'Nepal'}),
    ('NL', {'ar': 'هولندا',             'en': 'Netherlands',              'tr': 'Hollanda'}),
    ('NZ', {'ar': 'نيوزيلندا',           'en': 'New Zealand',              'tr': 'Yeni Zelanda'}),
    ('NI', {'ar': 'نيكاراغوا',           'en': 'Nicaragua',                'tr': 'Nikaragua'}),
    ('NE', {'ar': 'النيجر',             'en': 'Niger',                    'tr': 'Nijer'}),
    ('NG', {'ar': 'نيجيريا',            'en': 'Nigeria',                  'tr': 'Nijerya'}),
    ('MK', {'ar': 'شمال مقدونيا',       'en': 'North Macedonia',          'tr': 'Kuzey Makedonya'}),
    ('NO', {'ar': 'النرويج',            'en': 'Norway',                   'tr': 'Norveç'}),
    ('OM', {'ar': 'عُمان',              'en': 'Oman',                     'tr': 'Umman'}),
    ('PK', {'ar': 'باكستان',            'en': 'Pakistan',                 'tr': 'Pakistan'}),
    ('PW', {'ar': 'بالاو',              'en': 'Palau',                    'tr': 'Palau'}),
    ('PS', {'ar': 'فلسطين',             'en': 'Palestine',                'tr': 'Filistin'}),
    ('PA', {'ar': 'بنما',               'en': 'Panama',                   'tr': 'Panama'}),
    ('PG', {'ar': 'بابوا غينيا الجديدة','en': 'Papua New Guinea',         'tr': 'Papua Yeni Gine'}),
    ('PY', {'ar': 'باراغواي',           'en': 'Paraguay',                 'tr': 'Paraguay'}),
    ('PE', {'ar': 'بيرو',               'en': 'Peru',                     'tr': 'Peru'}),
    ('PH', {'ar': 'الفلبين',            'en': 'Philippines',              'tr': 'Filipinler'}),
    ('PL', {'ar': 'بولندا',             'en': 'Poland',                   'tr': 'Polonya'}),
    ('PT', {'ar': 'البرتغال',           'en': 'Portugal',                 'tr': 'Portekiz'}),
    ('QA', {'ar': 'قطر',               'en': 'Qatar',                    'tr': 'Katar'}),
    ('RO', {'ar': 'رومانيا',            'en': 'Romania',                  'tr': 'Romanya'}),
    ('RU', {'ar': 'روسيا',              'en': 'Russia',                   'tr': 'Rusya'}),
    ('RW', {'ar': 'رواندا',             'en': 'Rwanda',                   'tr': 'Ruanda'}),
    ('WS', {'ar': 'ساموا',              'en': 'Samoa',                    'tr': 'Samoa'}),
    ('SM', {'ar': 'سان مارينو',         'en': 'San Marino',               'tr': 'San Marino'}),
    ('ST', {'ar': 'ساو تومي وبرينسيبي', 'en': 'São Tomé and Príncipe',    'tr': 'Sao Tome ve Principe'}),
    ('SA', {'ar': 'السعودية',           'en': 'Saudi Arabia',             'tr': 'Suudi Arabistan'}),
    ('SN', {'ar': 'السنغال',            'en': 'Senegal',                  'tr': 'Senegal'}),
    ('RS', {'ar': 'صربيا',              'en': 'Serbia',                   'tr': 'Sırbistan'}),
    ('SL', {'ar': 'سيراليون',           'en': 'Sierra Leone',             'tr': 'Sierra Leone'}),
    ('SG', {'ar': 'سنغافورة',           'en': 'Singapore',                'tr': 'Singapur'}),
    ('SK', {'ar': 'سلوفاكيا',           'en': 'Slovakia',                 'tr': 'Slovakya'}),
    ('SI', {'ar': 'سلوفينيا',           'en': 'Slovenia',                 'tr': 'Slovenya'}),
    ('SB', {'ar': 'جزر سليمان',         'en': 'Solomon Islands',          'tr': 'Solomon Adaları'}),
    ('SO', {'ar': 'الصومال',            'en': 'Somalia',                  'tr': 'Somali'}),
    ('ZA', {'ar': 'جنوب أفريقيا',       'en': 'South Africa',             'tr': 'Güney Afrika'}),
    ('SS', {'ar': 'جنوب السودان',       'en': 'South Sudan',              'tr': 'Güney Sudan'}),
    ('ES', {'ar': 'إسبانيا',            'en': 'Spain',                    'tr': 'İspanya'}),
    ('LK', {'ar': 'سريلانكا',           'en': 'Sri Lanka',                'tr': 'Sri Lanka'}),
    ('SD', {'ar': 'السودان',            'en': 'Sudan',                    'tr': 'Sudan'}),
    ('SR', {'ar': 'سورينام',            'en': 'Suriname',                 'tr': 'Surinam'}),
    ('SE', {'ar': 'السويد',             'en': 'Sweden',                   'tr': 'İsveç'}),
    ('CH', {'ar': 'سويسرا',             'en': 'Switzerland',              'tr': 'İsviçre'}),
    ('SY', {'ar': 'سوريا',              'en': 'Syria',                    'tr': 'Suriye'}),
    ('TW', {'ar': 'تايوان',             'en': 'Taiwan',                   'tr': 'Tayvan'}),
    ('TJ', {'ar': 'طاجيكستان',          'en': 'Tajikistan',               'tr': 'Tacikistan'}),
    ('TZ', {'ar': 'تنزانيا',            'en': 'Tanzania',                 'tr': 'Tanzanya'}),
    ('TH', {'ar': 'تايلاند',            'en': 'Thailand',                 'tr': 'Tayland'}),
    ('TL', {'ar': 'تيمور الشرقية',      'en': 'Timor-Leste',              'tr': 'Doğu Timor'}),
    ('TG', {'ar': 'توغو',               'en': 'Togo',                     'tr': 'Togo'}),
    ('TO', {'ar': 'تونغا',              'en': 'Tonga',                    'tr': 'Tonga'}),
    ('TT', {'ar': 'ترينيداد وتوباغو',   'en': 'Trinidad and Tobago',      'tr': 'Trinidad ve Tobago'}),
    ('TN', {'ar': 'تونس',              'en': 'Tunisia',                  'tr': 'Tunus'}),
    ('TR', {'ar': 'تركيا',              'en': 'Turkey',                   'tr': 'Türkiye'}),
    ('TM', {'ar': 'تركمانستان',         'en': 'Turkmenistan',             'tr': 'Türkmenistan'}),
    ('TV', {'ar': 'توفالو',             'en': 'Tuvalu',                   'tr': 'Tuvalu'}),
    ('UG', {'ar': 'أوغندا',             'en': 'Uganda',                   'tr': 'Uganda'}),
    ('UA', {'ar': 'أوكرانيا',           'en': 'Ukraine',                  'tr': 'Ukrayna'}),
    ('AE', {'ar': 'الإمارات',           'en': 'United Arab Emirates',     'tr': 'Birleşik Arap Emirlikleri'}),
    ('GB', {'ar': 'المملكة المتحدة',    'en': 'United Kingdom',           'tr': 'Birleşik Krallık'}),
    ('US', {'ar': 'الولايات المتحدة',   'en': 'United States',            'tr': 'Amerika Birleşik Devletleri'}),
    ('UY', {'ar': 'الأوروغواي',         'en': 'Uruguay',                  'tr': 'Uruguay'}),
    ('UZ', {'ar': 'أوزبكستان',          'en': 'Uzbekistan',               'tr': 'Özbekistan'}),
    ('VU', {'ar': 'فانواتو',            'en': 'Vanuatu',                  'tr': 'Vanuatu'}),
    ('VE', {'ar': 'فنزويلا',            'en': 'Venezuela',                'tr': 'Venezuela'}),
    ('VN', {'ar': 'فيتنام',             'en': 'Vietnam',                  'tr': 'Vietnam'}),
    ('YE', {'ar': 'اليمن',              'en': 'Yemen',                    'tr': 'Yemen'}),
    ('ZM', {'ar': 'زامبيا',             'en': 'Zambia',                   'tr': 'Zambiya'}),
    ('ZW', {'ar': 'زيمبابوي',           'en': 'Zimbabwe',                 'tr': 'Zimbabve'}),
]


def get_countries(lang='ar'):
    """Return sorted list of (iso2, name) for given language."""
    lang = lang if lang in ('ar', 'en', 'tr') else 'ar'
    result = [(code, names[lang]) for code, names in _COUNTRIES]
    result.sort(key=lambda x: x[1])
    return result


# Phone dial codes per ISO2 country
_PHONE_CODES = {
    'AF':'+93','AL':'+355','DZ':'+213','AD':'+376','AO':'+244','AR':'+54',
    'AM':'+374','AU':'+61','AT':'+43','AZ':'+994','BH':'+973','BD':'+880',
    'BY':'+375','BE':'+32','BZ':'+501','BJ':'+229','BT':'+975','BO':'+591',
    'BA':'+387','BW':'+267','BR':'+55','BN':'+673','BG':'+359','BF':'+226',
    'BI':'+257','KH':'+855','CM':'+237','CA':'+1','CV':'+238','CF':'+236',
    'TD':'+235','CL':'+56','CN':'+86','CO':'+57','KM':'+269','CG':'+242',
    'CR':'+506','HR':'+385','CU':'+53','CY':'+357','CZ':'+420','DK':'+45',
    'DJ':'+253','DO':'+1','EC':'+593','EG':'+20','SV':'+503','GQ':'+240',
    'ER':'+291','EE':'+372','ET':'+251','FJ':'+679','FI':'+358','FR':'+33',
    'GA':'+241','GM':'+220','GE':'+995','DE':'+49','GH':'+233','GR':'+30',
    'GT':'+502','GN':'+224','GW':'+245','GY':'+592','HT':'+509','HN':'+504',
    'HU':'+36','IS':'+354','IN':'+91','ID':'+62','IR':'+98','IQ':'+964',
    'IE':'+353','IL':'+972','IT':'+39','JM':'+1','JP':'+81','JO':'+962',
    'KZ':'+7','KE':'+254','KI':'+686','KP':'+850','KR':'+82','KW':'+965',
    'KG':'+996','LA':'+856','LV':'+371','LB':'+961','LS':'+266','LR':'+231',
    'LY':'+218','LI':'+423','LT':'+370','LU':'+352','MG':'+261','MW':'+265',
    'MY':'+60','MV':'+960','ML':'+223','MT':'+356','MR':'+222','MU':'+230',
    'MX':'+52','FM':'+691','MD':'+373','MC':'+377','MN':'+976','ME':'+382',
    'MA':'+212','MZ':'+258','MM':'+95','NA':'+264','NP':'+977','NL':'+31',
    'NZ':'+64','NI':'+505','NE':'+227','NG':'+234','MK':'+389','NO':'+47',
    'OM':'+968','PK':'+92','PW':'+680','PS':'+970','PA':'+507','PG':'+675',
    'PY':'+595','PE':'+51','PH':'+63','PL':'+48','PT':'+351','QA':'+974',
    'RO':'+40','RU':'+7','RW':'+250','WS':'+685','SM':'+378','ST':'+239',
    'SA':'+966','SN':'+221','RS':'+381','SL':'+232','SG':'+65','SK':'+421',
    'SI':'+386','SB':'+677','SO':'+252','ZA':'+27','SS':'+211','ES':'+34',
    'LK':'+94','SD':'+249','SR':'+597','SE':'+46','CH':'+41','SY':'+963',
    'TW':'+886','TJ':'+992','TZ':'+255','TH':'+66','TL':'+670','TG':'+228',
    'TO':'+676','TT':'+1','TN':'+216','TR':'+90','TM':'+993','TV':'+688',
    'UG':'+256','UA':'+380','AE':'+971','GB':'+44','US':'+1','UY':'+598',
    'UZ':'+998','VU':'+678','VE':'+58','VN':'+84','YE':'+967','ZM':'+260',
    'ZW':'+263',
}


def get_phone_codes(lang='ar'):
    """Return sorted list of (dial_code, 'CountryName dial_code') for given language."""
    lang = lang if lang in ('ar', 'en', 'tr') else 'ar'
    result = []
    for iso2, names in _COUNTRIES:
        dial = _PHONE_CODES.get(iso2)
        if dial:
            result.append((dial, names[lang] + ' ' + dial))
    result.sort(key=lambda x: x[1])
    return result
